package org.quarkbit.trabajosocialsanjuan.dao.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class ConsultaExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table consulta
     *
     * @mbggenerated Sun Apr 13 16:11:45 CEST 2014
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table consulta
     *
     * @mbggenerated Sun Apr 13 16:11:45 CEST 2014
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table consulta
     *
     * @mbggenerated Sun Apr 13 16:11:45 CEST 2014
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consulta
     *
     * @mbggenerated Sun Apr 13 16:11:45 CEST 2014
     */
    public ConsultaExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consulta
     *
     * @mbggenerated Sun Apr 13 16:11:45 CEST 2014
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consulta
     *
     * @mbggenerated Sun Apr 13 16:11:45 CEST 2014
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consulta
     *
     * @mbggenerated Sun Apr 13 16:11:45 CEST 2014
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consulta
     *
     * @mbggenerated Sun Apr 13 16:11:45 CEST 2014
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consulta
     *
     * @mbggenerated Sun Apr 13 16:11:45 CEST 2014
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consulta
     *
     * @mbggenerated Sun Apr 13 16:11:45 CEST 2014
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consulta
     *
     * @mbggenerated Sun Apr 13 16:11:45 CEST 2014
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consulta
     *
     * @mbggenerated Sun Apr 13 16:11:45 CEST 2014
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consulta
     *
     * @mbggenerated Sun Apr 13 16:11:45 CEST 2014
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consulta
     *
     * @mbggenerated Sun Apr 13 16:11:45 CEST 2014
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table consulta
     *
     * @mbggenerated Sun Apr 13 16:11:45 CEST 2014
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andNumeroConsultaIsNull() {
            addCriterion("numero_consulta is null");
            return (Criteria) this;
        }

        public Criteria andNumeroConsultaIsNotNull() {
            addCriterion("numero_consulta is not null");
            return (Criteria) this;
        }

        public Criteria andNumeroConsultaEqualTo(Integer value) {
            addCriterion("numero_consulta =", value, "numeroConsulta");
            return (Criteria) this;
        }

        public Criteria andNumeroConsultaNotEqualTo(Integer value) {
            addCriterion("numero_consulta <>", value, "numeroConsulta");
            return (Criteria) this;
        }

        public Criteria andNumeroConsultaGreaterThan(Integer value) {
            addCriterion("numero_consulta >", value, "numeroConsulta");
            return (Criteria) this;
        }

        public Criteria andNumeroConsultaGreaterThanOrEqualTo(Integer value) {
            addCriterion("numero_consulta >=", value, "numeroConsulta");
            return (Criteria) this;
        }

        public Criteria andNumeroConsultaLessThan(Integer value) {
            addCriterion("numero_consulta <", value, "numeroConsulta");
            return (Criteria) this;
        }

        public Criteria andNumeroConsultaLessThanOrEqualTo(Integer value) {
            addCriterion("numero_consulta <=", value, "numeroConsulta");
            return (Criteria) this;
        }

        public Criteria andNumeroConsultaIn(List<Integer> values) {
            addCriterion("numero_consulta in", values, "numeroConsulta");
            return (Criteria) this;
        }

        public Criteria andNumeroConsultaNotIn(List<Integer> values) {
            addCriterion("numero_consulta not in", values, "numeroConsulta");
            return (Criteria) this;
        }

        public Criteria andNumeroConsultaBetween(Integer value1, Integer value2) {
            addCriterion("numero_consulta between", value1, value2, "numeroConsulta");
            return (Criteria) this;
        }

        public Criteria andNumeroConsultaNotBetween(Integer value1, Integer value2) {
            addCriterion("numero_consulta not between", value1, value2, "numeroConsulta");
            return (Criteria) this;
        }

        public Criteria andNumeroHistorialClinicoIsNull() {
            addCriterion("numero_hc is null");
            return (Criteria) this;
        }

        public Criteria andNumeroHistorialClinicoIsNotNull() {
            addCriterion("numero_hc is not null");
            return (Criteria) this;
        }

        public Criteria andNumeroHistorialClinicoEqualTo(Integer value) {
            addCriterion("numero_hc =", value, "numeroHistorialClinico");
            return (Criteria) this;
        }

        public Criteria andNumeroHistorialClinicoNotEqualTo(Integer value) {
            addCriterion("numero_hc <>", value, "numeroHistorialClinico");
            return (Criteria) this;
        }

        public Criteria andNumeroHistorialClinicoGreaterThan(Integer value) {
            addCriterion("numero_hc >", value, "numeroHistorialClinico");
            return (Criteria) this;
        }

        public Criteria andNumeroHistorialClinicoGreaterThanOrEqualTo(Integer value) {
            addCriterion("numero_hc >=", value, "numeroHistorialClinico");
            return (Criteria) this;
        }

        public Criteria andNumeroHistorialClinicoLessThan(Integer value) {
            addCriterion("numero_hc <", value, "numeroHistorialClinico");
            return (Criteria) this;
        }

        public Criteria andNumeroHistorialClinicoLessThanOrEqualTo(Integer value) {
            addCriterion("numero_hc <=", value, "numeroHistorialClinico");
            return (Criteria) this;
        }

        public Criteria andNumeroHistorialClinicoIn(List<Integer> values) {
            addCriterion("numero_hc in", values, "numeroHistorialClinico");
            return (Criteria) this;
        }

        public Criteria andNumeroHistorialClinicoNotIn(List<Integer> values) {
            addCriterion("numero_hc not in", values, "numeroHistorialClinico");
            return (Criteria) this;
        }

        public Criteria andNumeroHistorialClinicoBetween(Integer value1, Integer value2) {
            addCriterion("numero_hc between", value1, value2, "numeroHistorialClinico");
            return (Criteria) this;
        }

        public Criteria andNumeroHistorialClinicoNotBetween(Integer value1, Integer value2) {
            addCriterion("numero_hc not between", value1, value2, "numeroHistorialClinico");
            return (Criteria) this;
        }

        public Criteria andMotivoIsNull() {
            addCriterion("motivo is null");
            return (Criteria) this;
        }

        public Criteria andMotivoIsNotNull() {
            addCriterion("motivo is not null");
            return (Criteria) this;
        }

        public Criteria andMotivoEqualTo(String value) {
            addCriterion("motivo =", value, "motivo");
            return (Criteria) this;
        }

        public Criteria andMotivoNotEqualTo(String value) {
            addCriterion("motivo <>", value, "motivo");
            return (Criteria) this;
        }

        public Criteria andMotivoGreaterThan(String value) {
            addCriterion("motivo >", value, "motivo");
            return (Criteria) this;
        }

        public Criteria andMotivoGreaterThanOrEqualTo(String value) {
            addCriterion("motivo >=", value, "motivo");
            return (Criteria) this;
        }

        public Criteria andMotivoLessThan(String value) {
            addCriterion("motivo <", value, "motivo");
            return (Criteria) this;
        }

        public Criteria andMotivoLessThanOrEqualTo(String value) {
            addCriterion("motivo <=", value, "motivo");
            return (Criteria) this;
        }

        public Criteria andMotivoLike(String value) {
            addCriterion("upper(motivo) like", value, "motivo");
            return (Criteria) this;
        }

        public Criteria andMotivoNotLike(String value) {
            addCriterion("motivo not like", value, "motivo");
            return (Criteria) this;
        }

        public Criteria andMotivoIn(List<String> values) {
            addCriterion("motivo in", values, "motivo");
            return (Criteria) this;
        }

        public Criteria andMotivoNotIn(List<String> values) {
            addCriterion("motivo not in", values, "motivo");
            return (Criteria) this;
        }

        public Criteria andMotivoBetween(String value1, String value2) {
            addCriterion("motivo between", value1, value2, "motivo");
            return (Criteria) this;
        }

        public Criteria andMotivoNotBetween(String value1, String value2) {
            addCriterion("motivo not between", value1, value2, "motivo");
            return (Criteria) this;
        }

        public Criteria andFechaConsultaIsNull() {
            addCriterion("fecha_consulta is null");
            return (Criteria) this;
        }

        public Criteria andFechaConsultaIsNotNull() {
            addCriterion("fecha_consulta is not null");
            return (Criteria) this;
        }

        public Criteria andFechaConsultaEqualTo(Date value) {
            addCriterionForJDBCDate("fecha_consulta =", value, "fechaConsulta");
            return (Criteria) this;
        }

        public Criteria andFechaConsultaNotEqualTo(Date value) {
            addCriterionForJDBCDate("fecha_consulta <>", value, "fechaConsulta");
            return (Criteria) this;
        }

        public Criteria andFechaConsultaGreaterThan(Date value) {
            addCriterionForJDBCDate("fecha_consulta >", value, "fechaConsulta");
            return (Criteria) this;
        }

        public Criteria andFechaConsultaGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("fecha_consulta >=", value, "fechaConsulta");
            return (Criteria) this;
        }

        public Criteria andFechaConsultaLessThan(Date value) {
            addCriterionForJDBCDate("fecha_consulta <", value, "fechaConsulta");
            return (Criteria) this;
        }

        public Criteria andFechaConsultaLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("fecha_consulta <=", value, "fechaConsulta");
            return (Criteria) this;
        }

        public Criteria andFechaConsultaIn(List<Date> values) {
            addCriterionForJDBCDate("fecha_consulta in", values, "fechaConsulta");
            return (Criteria) this;
        }

        public Criteria andFechaConsultaNotIn(List<Date> values) {
            addCriterionForJDBCDate("fecha_consulta not in", values, "fechaConsulta");
            return (Criteria) this;
        }

        public Criteria andFechaConsultaBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("fecha_consulta between", value1, value2, "fechaConsulta");
            return (Criteria) this;
        }

        public Criteria andFechaConsultaNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("fecha_consulta not between", value1, value2, "fechaConsulta");
            return (Criteria) this;
        }

        public Criteria andCodigoTipoConsultaIsNull() {
            addCriterion("codigo_tipo_consulta is null");
            return (Criteria) this;
        }

        public Criteria andCodigoTipoConsultaIsNotNull() {
            addCriterion("codigo_tipo_consulta is not null");
            return (Criteria) this;
        }

        public Criteria andCodigoTipoConsultaEqualTo(String value) {
            addCriterion("codigo_tipo_consulta =", value, "codigoTipoConsulta");
            return (Criteria) this;
        }

        public Criteria andCodigoTipoConsultaNotEqualTo(String value) {
            addCriterion("codigo_tipo_consulta <>", value, "codigoTipoConsulta");
            return (Criteria) this;
        }

        public Criteria andCodigoTipoConsultaGreaterThan(String value) {
            addCriterion("codigo_tipo_consulta >", value, "codigoTipoConsulta");
            return (Criteria) this;
        }

        public Criteria andCodigoTipoConsultaGreaterThanOrEqualTo(String value) {
            addCriterion("codigo_tipo_consulta >=", value, "codigoTipoConsulta");
            return (Criteria) this;
        }

        public Criteria andCodigoTipoConsultaLessThan(String value) {
            addCriterion("codigo_tipo_consulta <", value, "codigoTipoConsulta");
            return (Criteria) this;
        }

        public Criteria andCodigoTipoConsultaLessThanOrEqualTo(String value) {
            addCriterion("codigo_tipo_consulta <=", value, "codigoTipoConsulta");
            return (Criteria) this;
        }

        public Criteria andCodigoTipoConsultaLike(String value) {
            addCriterion("codigo_tipo_consulta like", value, "codigoTipoConsulta");
            return (Criteria) this;
        }

        public Criteria andCodigoTipoConsultaNotLike(String value) {
            addCriterion("codigo_tipo_consulta not like", value, "codigoTipoConsulta");
            return (Criteria) this;
        }

        public Criteria andCodigoTipoConsultaIn(List<String> values) {
            addCriterion("codigo_tipo_consulta in", values, "codigoTipoConsulta");
            return (Criteria) this;
        }

        public Criteria andCodigoTipoConsultaNotIn(List<String> values) {
            addCriterion("codigo_tipo_consulta not in", values, "codigoTipoConsulta");
            return (Criteria) this;
        }

        public Criteria andCodigoTipoConsultaBetween(String value1, String value2) {
            addCriterion("codigo_tipo_consulta between", value1, value2, "codigoTipoConsulta");
            return (Criteria) this;
        }

        public Criteria andCodigoTipoConsultaNotBetween(String value1, String value2) {
            addCriterion("codigo_tipo_consulta not between", value1, value2, "codigoTipoConsulta");
            return (Criteria) this;
        }

        public Criteria andDiagnosticoIsNull() {
            addCriterion("diagnostico is null");
            return (Criteria) this;
        }

        public Criteria andDiagnosticoIsNotNull() {
            addCriterion("diagnostico is not null");
            return (Criteria) this;
        }

        public Criteria andDiagnosticoEqualTo(String value) {
            addCriterion("diagnostico =", value, "diagnostico");
            return (Criteria) this;
        }

        public Criteria andDiagnosticoNotEqualTo(String value) {
            addCriterion("diagnostico <>", value, "diagnostico");
            return (Criteria) this;
        }

        public Criteria andDiagnosticoGreaterThan(String value) {
            addCriterion("diagnostico >", value, "diagnostico");
            return (Criteria) this;
        }

        public Criteria andDiagnosticoGreaterThanOrEqualTo(String value) {
            addCriterion("diagnostico >=", value, "diagnostico");
            return (Criteria) this;
        }

        public Criteria andDiagnosticoLessThan(String value) {
            addCriterion("diagnostico <", value, "diagnostico");
            return (Criteria) this;
        }

        public Criteria andDiagnosticoLessThanOrEqualTo(String value) {
            addCriterion("diagnostico <=", value, "diagnostico");
            return (Criteria) this;
        }

        public Criteria andDiagnosticoLike(String value) {
            addCriterion("upper(diagnostico) like", value, "diagnostico");
            return (Criteria) this;
        }

        public Criteria andDiagnosticoNotLike(String value) {
            addCriterion("diagnostico not like", value, "diagnostico");
            return (Criteria) this;
        }

        public Criteria andDiagnosticoIn(List<String> values) {
            addCriterion("diagnostico in", values, "diagnostico");
            return (Criteria) this;
        }

        public Criteria andDiagnosticoNotIn(List<String> values) {
            addCriterion("diagnostico not in", values, "diagnostico");
            return (Criteria) this;
        }

        public Criteria andDiagnosticoBetween(String value1, String value2) {
            addCriterion("diagnostico between", value1, value2, "diagnostico");
            return (Criteria) this;
        }

        public Criteria andDiagnosticoNotBetween(String value1, String value2) {
            addCriterion("diagnostico not between", value1, value2, "diagnostico");
            return (Criteria) this;
        }

        public Criteria andObservacionesIsNull() {
            addCriterion("observaciones is null");
            return (Criteria) this;
        }

        public Criteria andObservacionesIsNotNull() {
            addCriterion("observaciones is not null");
            return (Criteria) this;
        }

        public Criteria andObservacionesEqualTo(String value) {
            addCriterion("observaciones =", value, "observaciones");
            return (Criteria) this;
        }

        public Criteria andObservacionesNotEqualTo(String value) {
            addCriterion("observaciones <>", value, "observaciones");
            return (Criteria) this;
        }

        public Criteria andObservacionesGreaterThan(String value) {
            addCriterion("observaciones >", value, "observaciones");
            return (Criteria) this;
        }

        public Criteria andObservacionesGreaterThanOrEqualTo(String value) {
            addCriterion("observaciones >=", value, "observaciones");
            return (Criteria) this;
        }

        public Criteria andObservacionesLessThan(String value) {
            addCriterion("observaciones <", value, "observaciones");
            return (Criteria) this;
        }

        public Criteria andObservacionesLessThanOrEqualTo(String value) {
            addCriterion("observaciones <=", value, "observaciones");
            return (Criteria) this;
        }

        public Criteria andObservacionesLike(String value) {
            addCriterion("upper(observaciones) like", value, "observaciones");
            return (Criteria) this;
        }

        public Criteria andObservacionesNotLike(String value) {
            addCriterion("observaciones not like", value, "observaciones");
            return (Criteria) this;
        }

        public Criteria andObservacionesIn(List<String> values) {
            addCriterion("observaciones in", values, "observaciones");
            return (Criteria) this;
        }

        public Criteria andObservacionesNotIn(List<String> values) {
            addCriterion("observaciones not in", values, "observaciones");
            return (Criteria) this;
        }

        public Criteria andObservacionesBetween(String value1, String value2) {
            addCriterion("observaciones between", value1, value2, "observaciones");
            return (Criteria) this;
        }

        public Criteria andObservacionesNotBetween(String value1, String value2) {
            addCriterion("observaciones not between", value1, value2, "observaciones");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table consulta
     *
     * @mbggenerated do_not_delete_during_merge Sun Apr 13 16:11:45 CEST 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table consulta
     *
     * @mbggenerated Sun Apr 13 16:11:45 CEST 2014
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}