package org.quarkbit.trabajosocialsanjuan.dao.domain;

import java.util.Date;

public class HistorialClinicoConsultaDetalle {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column historia_clinico_consulta_detalle.numero_hc_consulta_detalle
     *
     * @mbggenerated Sun Apr 13 16:11:45 CEST 2014
     */
    private Integer numeroHCConsultaDetalle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column historia_clinico_consulta_detalle.numero_hc
     *
     * @mbggenerated Sun Apr 13 16:11:45 CEST 2014
     */
    private Integer numeroHistorialClinico;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column historia_clinico_consulta_detalle.numero_propiedad_tipo
     *
     * @mbggenerated Sun Apr 13 16:11:45 CEST 2014
     */
    private Integer numeroPropiedadTipo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column historia_clinico_consulta_detalle.numero_consulta
     *
     * @mbggenerated Sun Apr 13 16:11:45 CEST 2014
     */
    private Integer numeroConsulta;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column historia_clinico_consulta_detalle.numero_propiedad
     *
     * @mbggenerated Sun Apr 13 16:11:45 CEST 2014
     */
    private Integer numeroPropiedad;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column historia_clinico_consulta_detalle.fecha_registro
     *
     * @mbggenerated Sun Apr 13 16:11:45 CEST 2014
     */
    private Date fechaRegistro;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column historia_clinico_consulta_detalle.descripcion
     *
     * @mbggenerated Sun Apr 13 16:11:45 CEST 2014
     */
    private String descripcion;
    private PropiedadHistorialClinico propiedadHistorialClinico;
    private PropiedadTipo propiedadTipo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column historia_clinico_consulta_detalle.numero_hc_consulta_detalle
     *
     * @return the value of historia_clinico_consulta_detalle.numero_hc_consulta_detalle
     *
     * @mbggenerated Sun Apr 13 16:11:45 CEST 2014
     */
    public Integer getNumeroHCConsultaDetalle() {
        return numeroHCConsultaDetalle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column historia_clinico_consulta_detalle.numero_hc_consulta_detalle
     *
     * @param numeroHCConsultaDetalle the value for historia_clinico_consulta_detalle.numero_hc_consulta_detalle
     *
     * @mbggenerated Sun Apr 13 16:11:45 CEST 2014
     */
    public void setNumeroHCConsultaDetalle(Integer numeroHCConsultaDetalle) {
        this.numeroHCConsultaDetalle = numeroHCConsultaDetalle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column historia_clinico_consulta_detalle.numero_hc
     *
     * @return the value of historia_clinico_consulta_detalle.numero_hc
     *
     * @mbggenerated Sun Apr 13 16:11:45 CEST 2014
     */
    public Integer getNumeroHistorialClinico() {
        return numeroHistorialClinico;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column historia_clinico_consulta_detalle.numero_hc
     *
     * @param numeroHistorialClinico the value for historia_clinico_consulta_detalle.numero_hc
     *
     * @mbggenerated Sun Apr 13 16:11:45 CEST 2014
     */
    public void setNumeroHistorialClinico(Integer numeroHistorialClinico) {
        this.numeroHistorialClinico = numeroHistorialClinico;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column historia_clinico_consulta_detalle.numero_propiedad_tipo
     *
     * @return the value of historia_clinico_consulta_detalle.numero_propiedad_tipo
     *
     * @mbggenerated Sun Apr 13 16:11:45 CEST 2014
     */
    public Integer getNumeroPropiedadTipo() {
        return numeroPropiedadTipo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column historia_clinico_consulta_detalle.numero_propiedad_tipo
     *
     * @param numeroPropiedadTipo the value for historia_clinico_consulta_detalle.numero_propiedad_tipo
     *
     * @mbggenerated Sun Apr 13 16:11:45 CEST 2014
     */
    public void setNumeroPropiedadTipo(Integer numeroPropiedadTipo) {
        this.numeroPropiedadTipo = numeroPropiedadTipo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column historia_clinico_consulta_detalle.numero_consulta
     *
     * @return the value of historia_clinico_consulta_detalle.numero_consulta
     *
     * @mbggenerated Sun Apr 13 16:11:45 CEST 2014
     */
    public Integer getNumeroConsulta() {
        return numeroConsulta;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column historia_clinico_consulta_detalle.numero_consulta
     *
     * @param numeroConsulta the value for historia_clinico_consulta_detalle.numero_consulta
     *
     * @mbggenerated Sun Apr 13 16:11:45 CEST 2014
     */
    public void setNumeroConsulta(Integer numeroConsulta) {
        this.numeroConsulta = numeroConsulta;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column historia_clinico_consulta_detalle.numero_propiedad
     *
     * @return the value of historia_clinico_consulta_detalle.numero_propiedad
     *
     * @mbggenerated Sun Apr 13 16:11:45 CEST 2014
     */
    public Integer getNumeroPropiedad() {
        return numeroPropiedad;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column historia_clinico_consulta_detalle.numero_propiedad
     *
     * @param numeroPropiedad the value for historia_clinico_consulta_detalle.numero_propiedad
     *
     * @mbggenerated Sun Apr 13 16:11:45 CEST 2014
     */
    public void setNumeroPropiedad(Integer numeroPropiedad) {
        this.numeroPropiedad = numeroPropiedad;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column historia_clinico_consulta_detalle.fecha_registro
     *
     * @return the value of historia_clinico_consulta_detalle.fecha_registro
     *
     * @mbggenerated Sun Apr 13 16:11:45 CEST 2014
     */
    public Date getFechaRegistro() {
        return fechaRegistro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column historia_clinico_consulta_detalle.fecha_registro
     *
     * @param fechaRegistro the value for historia_clinico_consulta_detalle.fecha_registro
     *
     * @mbggenerated Sun Apr 13 16:11:45 CEST 2014
     */
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column historia_clinico_consulta_detalle.descripcion
     *
     * @return the value of historia_clinico_consulta_detalle.descripcion
     *
     * @mbggenerated Sun Apr 13 16:11:45 CEST 2014
     */
    public String getDescripcion() {
        return descripcion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column historia_clinico_consulta_detalle.descripcion
     *
     * @param descripcion the value for historia_clinico_consulta_detalle.descripcion
     *
     * @mbggenerated Sun Apr 13 16:11:45 CEST 2014
     */
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion == null ? null : descripcion.trim();
    }

	public PropiedadHistorialClinico getPropiedadHistorialClinico() {
		return propiedadHistorialClinico;
	}

	public void setPropiedadHistorialClinico(PropiedadHistorialClinico propiedadHistorialClinico) {
		this.propiedadHistorialClinico = propiedadHistorialClinico;
	}

	public PropiedadTipo getPropiedadTipo() {
		return propiedadTipo;
	}

	public void setPropiedadTipo(PropiedadTipo propiedadTipo) {
		this.propiedadTipo = propiedadTipo;
	}
}