package org.quarkbit.trabajosocialsanjuan.dao.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class HistorialClinicoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table historia_clinico
     *
     * @mbggenerated Sun Apr 13 16:11:45 CEST 2014
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table historia_clinico
     *
     * @mbggenerated Sun Apr 13 16:11:45 CEST 2014
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table historia_clinico
     *
     * @mbggenerated Sun Apr 13 16:11:45 CEST 2014
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table historia_clinico
     *
     * @mbggenerated Sun Apr 13 16:11:45 CEST 2014
     */
    public HistorialClinicoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table historia_clinico
     *
     * @mbggenerated Sun Apr 13 16:11:45 CEST 2014
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table historia_clinico
     *
     * @mbggenerated Sun Apr 13 16:11:45 CEST 2014
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table historia_clinico
     *
     * @mbggenerated Sun Apr 13 16:11:45 CEST 2014
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table historia_clinico
     *
     * @mbggenerated Sun Apr 13 16:11:45 CEST 2014
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table historia_clinico
     *
     * @mbggenerated Sun Apr 13 16:11:45 CEST 2014
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table historia_clinico
     *
     * @mbggenerated Sun Apr 13 16:11:45 CEST 2014
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table historia_clinico
     *
     * @mbggenerated Sun Apr 13 16:11:45 CEST 2014
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table historia_clinico
     *
     * @mbggenerated Sun Apr 13 16:11:45 CEST 2014
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table historia_clinico
     *
     * @mbggenerated Sun Apr 13 16:11:45 CEST 2014
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table historia_clinico
     *
     * @mbggenerated Sun Apr 13 16:11:45 CEST 2014
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table historia_clinico
     *
     * @mbggenerated Sun Apr 13 16:11:45 CEST 2014
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andNumeroHistorialClinicoIsNull() {
            addCriterion("numero_hc is null");
            return (Criteria) this;
        }

        public Criteria andNumeroHistorialClinicoIsNotNull() {
            addCriterion("numero_hc is not null");
            return (Criteria) this;
        }

        public Criteria andNumeroHistorialClinicoEqualTo(Integer value) {
            addCriterion("numero_hc =", value, "numeroHistorialClinico");
            return (Criteria) this;
        }

        public Criteria andNumeroHistorialClinicoNotEqualTo(Integer value) {
            addCriterion("numero_hc <>", value, "numeroHistorialClinico");
            return (Criteria) this;
        }

        public Criteria andNumeroHistorialClinicoGreaterThan(Integer value) {
            addCriterion("numero_hc >", value, "numeroHistorialClinico");
            return (Criteria) this;
        }

        public Criteria andNumeroHistorialClinicoGreaterThanOrEqualTo(Integer value) {
            addCriterion("numero_hc >=", value, "numeroHistorialClinico");
            return (Criteria) this;
        }

        public Criteria andNumeroHistorialClinicoLessThan(Integer value) {
            addCriterion("numero_hc <", value, "numeroHistorialClinico");
            return (Criteria) this;
        }

        public Criteria andNumeroHistorialClinicoLessThanOrEqualTo(Integer value) {
            addCriterion("numero_hc <=", value, "numeroHistorialClinico");
            return (Criteria) this;
        }

        public Criteria andNumeroHistorialClinicoIn(List<Integer> values) {
            addCriterion("numero_hc in", values, "numeroHistorialClinico");
            return (Criteria) this;
        }

        public Criteria andNumeroHistorialClinicoNotIn(List<Integer> values) {
            addCriterion("numero_hc not in", values, "numeroHistorialClinico");
            return (Criteria) this;
        }

        public Criteria andNumeroHistorialClinicoBetween(Integer value1, Integer value2) {
            addCriterion("numero_hc between", value1, value2, "numeroHistorialClinico");
            return (Criteria) this;
        }

        public Criteria andNumeroHistorialClinicoNotBetween(Integer value1, Integer value2) {
            addCriterion("numero_hc not between", value1, value2, "numeroHistorialClinico");
            return (Criteria) this;
        }

        public Criteria andIdPersonaIsNull() {
            addCriterion("idpersona is null");
            return (Criteria) this;
        }

        public Criteria andIdPersonaIsNotNull() {
            addCriterion("idpersona is not null");
            return (Criteria) this;
        }

        public Criteria andIdPersonaEqualTo(Integer value) {
            addCriterion("idpersona =", value, "idPersona");
            return (Criteria) this;
        }

        public Criteria andIdPersonaNotEqualTo(Integer value) {
            addCriterion("idpersona <>", value, "idPersona");
            return (Criteria) this;
        }

        public Criteria andIdPersonaGreaterThan(Integer value) {
            addCriterion("idpersona >", value, "idPersona");
            return (Criteria) this;
        }

        public Criteria andIdPersonaGreaterThanOrEqualTo(Integer value) {
            addCriterion("idpersona >=", value, "idPersona");
            return (Criteria) this;
        }

        public Criteria andIdPersonaLessThan(Integer value) {
            addCriterion("idpersona <", value, "idPersona");
            return (Criteria) this;
        }

        public Criteria andIdPersonaLessThanOrEqualTo(Integer value) {
            addCriterion("idpersona <=", value, "idPersona");
            return (Criteria) this;
        }

        public Criteria andIdPersonaIn(List<Integer> values) {
            addCriterion("idpersona in", values, "idPersona");
            return (Criteria) this;
        }

        public Criteria andIdPersonaNotIn(List<Integer> values) {
            addCriterion("idpersona not in", values, "idPersona");
            return (Criteria) this;
        }

        public Criteria andIdPersonaBetween(Integer value1, Integer value2) {
            addCriterion("idpersona between", value1, value2, "idPersona");
            return (Criteria) this;
        }

        public Criteria andIdPersonaNotBetween(Integer value1, Integer value2) {
            addCriterion("idpersona not between", value1, value2, "idPersona");
            return (Criteria) this;
        }

        public Criteria andGrupoSanguinioIsNull() {
            addCriterion("grupo_sanguinio is null");
            return (Criteria) this;
        }

        public Criteria andGrupoSanguinioIsNotNull() {
            addCriterion("grupo_sanguinio is not null");
            return (Criteria) this;
        }

        public Criteria andGrupoSanguinioEqualTo(String value) {
            addCriterion("grupo_sanguinio =", value, "grupoSanguinio");
            return (Criteria) this;
        }

        public Criteria andGrupoSanguinioNotEqualTo(String value) {
            addCriterion("grupo_sanguinio <>", value, "grupoSanguinio");
            return (Criteria) this;
        }

        public Criteria andGrupoSanguinioGreaterThan(String value) {
            addCriterion("grupo_sanguinio >", value, "grupoSanguinio");
            return (Criteria) this;
        }

        public Criteria andGrupoSanguinioGreaterThanOrEqualTo(String value) {
            addCriterion("grupo_sanguinio >=", value, "grupoSanguinio");
            return (Criteria) this;
        }

        public Criteria andGrupoSanguinioLessThan(String value) {
            addCriterion("grupo_sanguinio <", value, "grupoSanguinio");
            return (Criteria) this;
        }

        public Criteria andGrupoSanguinioLessThanOrEqualTo(String value) {
            addCriterion("grupo_sanguinio <=", value, "grupoSanguinio");
            return (Criteria) this;
        }

        public Criteria andGrupoSanguinioLike(String value) {
            addCriterion("grupo_sanguinio like", value, "grupoSanguinio");
            return (Criteria) this;
        }

        public Criteria andGrupoSanguinioNotLike(String value) {
            addCriterion("grupo_sanguinio not like", value, "grupoSanguinio");
            return (Criteria) this;
        }

        public Criteria andGrupoSanguinioIn(List<String> values) {
            addCriterion("grupo_sanguinio in", values, "grupoSanguinio");
            return (Criteria) this;
        }

        public Criteria andGrupoSanguinioNotIn(List<String> values) {
            addCriterion("grupo_sanguinio not in", values, "grupoSanguinio");
            return (Criteria) this;
        }

        public Criteria andGrupoSanguinioBetween(String value1, String value2) {
            addCriterion("grupo_sanguinio between", value1, value2, "grupoSanguinio");
            return (Criteria) this;
        }

        public Criteria andGrupoSanguinioNotBetween(String value1, String value2) {
            addCriterion("grupo_sanguinio not between", value1, value2, "grupoSanguinio");
            return (Criteria) this;
        }

        public Criteria andFecha_registroIsNull() {
            addCriterion("fecha_registro is null");
            return (Criteria) this;
        }

        public Criteria andFecha_registroIsNotNull() {
            addCriterion("fecha_registro is not null");
            return (Criteria) this;
        }

        public Criteria andFecha_registroEqualTo(Date value) {
            addCriterionForJDBCDate("fecha_registro =", value, "fecha_registro");
            return (Criteria) this;
        }

        public Criteria andFecha_registroNotEqualTo(Date value) {
            addCriterionForJDBCDate("fecha_registro <>", value, "fecha_registro");
            return (Criteria) this;
        }

        public Criteria andFecha_registroGreaterThan(Date value) {
            addCriterionForJDBCDate("fecha_registro >", value, "fecha_registro");
            return (Criteria) this;
        }

        public Criteria andFecha_registroGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("fecha_registro >=", value, "fecha_registro");
            return (Criteria) this;
        }

        public Criteria andFecha_registroLessThan(Date value) {
            addCriterionForJDBCDate("fecha_registro <", value, "fecha_registro");
            return (Criteria) this;
        }

        public Criteria andFecha_registroLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("fecha_registro <=", value, "fecha_registro");
            return (Criteria) this;
        }

        public Criteria andFecha_registroIn(List<Date> values) {
            addCriterionForJDBCDate("fecha_registro in", values, "fecha_registro");
            return (Criteria) this;
        }

        public Criteria andFecha_registroNotIn(List<Date> values) {
            addCriterionForJDBCDate("fecha_registro not in", values, "fecha_registro");
            return (Criteria) this;
        }

        public Criteria andFecha_registroBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("fecha_registro between", value1, value2, "fecha_registro");
            return (Criteria) this;
        }

        public Criteria andFecha_registroNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("fecha_registro not between", value1, value2, "fecha_registro");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table historia_clinico
     *
     * @mbggenerated do_not_delete_during_merge Sun Apr 13 16:11:45 CEST 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table historia_clinico
     *
     * @mbggenerated Sun Apr 13 16:11:45 CEST 2014
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}