package org.quarkbit.trabajosocialsanjuan.dao.domain;

import java.util.Date;

public class HistorialClinico {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column historia_clinico.numero_hc
     *
     * @mbggenerated Sun Apr 13 16:11:45 CEST 2014
     */
    private Integer numeroHistorialClinico;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column historia_clinico.idpersona
     *
     * @mbggenerated Sun Apr 13 16:11:45 CEST 2014
     */
    private Integer idPersona;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column historia_clinico.grupo_sanguinio
     *
     * @mbggenerated Sun Apr 13 16:11:45 CEST 2014
     */
    private String grupoSanguinio;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column historia_clinico.fecha_registro
     *
     * @mbggenerated Sun Apr 13 16:11:45 CEST 2014
     */
    private Date fecha_registro;
    
    private Persona persona;
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column historia_clinico.numero_hc
     *
     * @return the value of historia_clinico.numero_hc
     *
     * @mbggenerated Sun Apr 13 16:11:45 CEST 2014
     */
    public Integer getNumeroHistorialClinico() {
        return numeroHistorialClinico;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column historia_clinico.numero_hc
     *
     * @param numeroHistorialClinico the value for historia_clinico.numero_hc
     *
     * @mbggenerated Sun Apr 13 16:11:45 CEST 2014
     */
    public void setNumeroHistorialClinico(Integer numeroHistorialClinico) {
        this.numeroHistorialClinico = numeroHistorialClinico;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column historia_clinico.idpersona
     *
     * @return the value of historia_clinico.idpersona
     *
     * @mbggenerated Sun Apr 13 16:11:45 CEST 2014
     */
    public Integer getIdPersona() {
        return idPersona;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column historia_clinico.idpersona
     *
     * @param idPersona the value for historia_clinico.idpersona
     *
     * @mbggenerated Sun Apr 13 16:11:45 CEST 2014
     */
    public void setIdPersona(Integer idPersona) {
        this.idPersona = idPersona;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column historia_clinico.grupo_sanguinio
     *
     * @return the value of historia_clinico.grupo_sanguinio
     *
     * @mbggenerated Sun Apr 13 16:11:45 CEST 2014
     */
    public String getGrupoSanguinio() {
        return grupoSanguinio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column historia_clinico.grupo_sanguinio
     *
     * @param grupoSanguinio the value for historia_clinico.grupo_sanguinio
     *
     * @mbggenerated Sun Apr 13 16:11:45 CEST 2014
     */
    public void setGrupoSanguinio(String grupoSanguinio) {
        this.grupoSanguinio = grupoSanguinio == null ? null : grupoSanguinio.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column historia_clinico.fecha_registro
     *
     * @return the value of historia_clinico.fecha_registro
     *
     * @mbggenerated Sun Apr 13 16:11:45 CEST 2014
     */
    public Date getFecha_registro() {
        return fecha_registro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column historia_clinico.fecha_registro
     *
     * @param fecha_registro the value for historia_clinico.fecha_registro
     *
     * @mbggenerated Sun Apr 13 16:11:45 CEST 2014
     */
    public void setFecha_registro(Date fecha_registro) {
        this.fecha_registro = fecha_registro;
    }

	public Persona getPersona() {
		return persona;
	}

	public void setPersona(Persona persona) {
		this.persona = persona;
	}
}