package org.quarkbit.trabajosocialsanjuan.dao.domain;

import java.util.Date;

public class Informe {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column informes.codigo_informe
     *
     * @mbggenerated Tue Mar 04 17:35:56 BOT 2014
     */
    private Integer codigoInforme;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column informes.codigo_kardex
     *
     * @mbggenerated Tue Mar 04 17:35:56 BOT 2014
     */
    private Integer codigoKardex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column informes.codigo_institucion
     *
     * @mbggenerated Tue Mar 04 17:35:56 BOT 2014
     */
    private Integer codigoInstitucion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column informes.codigo_tipo_informe
     *
     * @mbggenerated Tue Mar 04 17:35:56 BOT 2014
     */
    private String codigoTipoInforme;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column informes.codigo_persona_dirigido
     *
     * @mbggenerated Tue Mar 04 17:35:56 BOT 2014
     */
    private Integer codigoPersonaDirigido;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column informes.codigo_persona_via
     *
     * @mbggenerated Tue Mar 04 17:35:56 BOT 2014
     */
    private Integer codigoPersonaVia;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column informes.codigo_persona_de_01
     *
     * @mbggenerated Tue Mar 04 17:35:56 BOT 2014
     */
    private Integer codigoPersonaDe1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column informes.codigo_persona_de_02
     *
     * @mbggenerated Tue Mar 04 17:35:56 BOT 2014
     */
    private Integer codigoPersonaDe2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column informes.codigo_persona_de_03
     *
     * @mbggenerated Tue Mar 04 17:35:57 BOT 2014
     */
    private Integer codigoPersonaDe3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column informes.referencia
     *
     * @mbggenerated Tue Mar 04 17:35:57 BOT 2014
     */
    private String referencia;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column informes.fecha_registro
     *
     * @mbggenerated Tue Mar 04 17:35:57 BOT 2014
     */
    private Date fechaRegistro;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column informes.fecha_envio
     *
     * @mbggenerated Tue Mar 04 17:35:57 BOT 2014
     */
    private Date fechaEnvio;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column informes.diagnostico
     *
     * @mbggenerated Tue Mar 04 17:35:57 BOT 2014
     */
    private String diagnostico;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column informes.sugerencias
     *
     * @mbggenerated Tue Mar 04 17:35:57 BOT 2014
     */
    private String sugerencias;
    
    private Persona personaA;
    private Persona personaVia;
    private Persona personaDe1;
    private Persona personaDe2;
    private Persona personaDe3;    
    private PersonaKardex personaKardex;
    private Persona nino;
    
    public Persona getPersonaA() {
		return personaA;
	}

	public void setPersonaA(Persona personaA) {
		this.personaA = personaA;
	}

	public Persona getPersonaVia() {
		return personaVia;
	}

	public void setPersonaVia(Persona personaVia) {
		this.personaVia = personaVia;
	}

	public Persona getPersonaDe1() {
		return personaDe1;
	}

	public void setPersonaDe1(Persona personaDe1) {
		this.personaDe1 = personaDe1;
	}

	public Persona getPersonaDe2() {
		return personaDe2;
	}

	public void setPersonaDe2(Persona personaDe2) {
		this.personaDe2 = personaDe2;
	}

	public Persona getPersonaDe3() {
		return personaDe3;
	}

	public void setPersonaDe3(Persona personaDe3) {
		this.personaDe3 = personaDe3;
	}

	public PersonaKardex getPersonaKardex() {
		return personaKardex;
	}

	public void setPersonaKardex(PersonaKardex personaKardex) {
		this.personaKardex = personaKardex;
	}

	
    
   
	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column informes.codigo_informe
     *
     * @return the value of informes.codigo_informe
     *
     * @mbggenerated Tue Mar 04 17:35:56 BOT 2014
     */
    public Integer getCodigoInforme() {
        return codigoInforme;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column informes.codigo_informe
     *
     * @param codigoInforme the value for informes.codigo_informe
     *
     * @mbggenerated Tue Mar 04 17:35:56 BOT 2014
     */
    public void setCodigoInforme(Integer codigoInforme) {
        this.codigoInforme = codigoInforme;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column informes.codigo_kardex
     *
     * @return the value of informes.codigo_kardex
     *
     * @mbggenerated Tue Mar 04 17:35:56 BOT 2014
     */
    public Integer getCodigoKardex() {
        return codigoKardex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column informes.codigo_kardex
     *
     * @param codigoKardex the value for informes.codigo_kardex
     *
     * @mbggenerated Tue Mar 04 17:35:56 BOT 2014
     */
    public void setCodigoKardex(Integer codigoKardex) {
        this.codigoKardex = codigoKardex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column informes.codigo_institucion
     *
     * @return the value of informes.codigo_institucion
     *
     * @mbggenerated Tue Mar 04 17:35:56 BOT 2014
     */
    public Integer getCodigoInstitucion() {
        return codigoInstitucion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column informes.codigo_institucion
     *
     * @param codigoInstitucion the value for informes.codigo_institucion
     *
     * @mbggenerated Tue Mar 04 17:35:56 BOT 2014
     */
    public void setCodigoInstitucion(Integer codigoInstitucion) {
        this.codigoInstitucion = codigoInstitucion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column informes.codigo_tipo_informe
     *
     * @return the value of informes.codigo_tipo_informe
     *
     * @mbggenerated Tue Mar 04 17:35:56 BOT 2014
     */
    public String getCodigoTipoInforme() {
        return codigoTipoInforme;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column informes.codigo_tipo_informe
     *
     * @param codigoTipoInforme the value for informes.codigo_tipo_informe
     *
     * @mbggenerated Tue Mar 04 17:35:56 BOT 2014
     */
    public void setCodigoTipoInforme(String codigoTipoInforme) {
        this.codigoTipoInforme = codigoTipoInforme == null ? null : codigoTipoInforme.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column informes.codigo_persona_dirigido
     *
     * @return the value of informes.codigo_persona_dirigido
     *
     * @mbggenerated Tue Mar 04 17:35:56 BOT 2014
     */
    public Integer getCodigoPersonaDirigido() {
        return codigoPersonaDirigido;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column informes.codigo_persona_dirigido
     *
     * @param codigoPersonaDirigido the value for informes.codigo_persona_dirigido
     *
     * @mbggenerated Tue Mar 04 17:35:56 BOT 2014
     */
    public void setCodigoPersonaDirigido(Integer codigoPersonaDirigido) {
        this.codigoPersonaDirigido = codigoPersonaDirigido;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column informes.codigo_persona_via
     *
     * @return the value of informes.codigo_persona_via
     *
     * @mbggenerated Tue Mar 04 17:35:56 BOT 2014
     */
    public Integer getCodigoPersonaVia() {
        return codigoPersonaVia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column informes.codigo_persona_via
     *
     * @param codigoPersonaVia the value for informes.codigo_persona_via
     *
     * @mbggenerated Tue Mar 04 17:35:56 BOT 2014
     */
    public void setCodigoPersonaVia(Integer codigoPersonaVia) {
        this.codigoPersonaVia = codigoPersonaVia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column informes.codigo_persona_de_01
     *
     * @return the value of informes.codigo_persona_de_01
     *
     * @mbggenerated Tue Mar 04 17:35:56 BOT 2014
     */
    public Integer getCodigoPersonaDe1() {
        return codigoPersonaDe1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column informes.codigo_persona_de_01
     *
     * @param codigoPersonaDe1 the value for informes.codigo_persona_de_01
     *
     * @mbggenerated Tue Mar 04 17:35:56 BOT 2014
     */
    public void setCodigoPersonaDe1(Integer codigoPersonaDe1) {
        this.codigoPersonaDe1 = codigoPersonaDe1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column informes.codigo_persona_de_02
     *
     * @return the value of informes.codigo_persona_de_02
     *
     * @mbggenerated Tue Mar 04 17:35:57 BOT 2014
     */
    public Integer getCodigoPersonaDe2() {
        return codigoPersonaDe2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column informes.codigo_persona_de_02
     *
     * @param codigoPersonaDe2 the value for informes.codigo_persona_de_02
     *
     * @mbggenerated Tue Mar 04 17:35:57 BOT 2014
     */
    public void setCodigoPersonaDe2(Integer codigoPersonaDe2) {
        this.codigoPersonaDe2 = codigoPersonaDe2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column informes.codigo_persona_de_03
     *
     * @return the value of informes.codigo_persona_de_03
     *
     * @mbggenerated Tue Mar 04 17:35:57 BOT 2014
     */
    public Integer getCodigoPersonaDe3() {
        return codigoPersonaDe3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column informes.codigo_persona_de_03
     *
     * @param codigoPersonaDe3 the value for informes.codigo_persona_de_03
     *
     * @mbggenerated Tue Mar 04 17:35:57 BOT 2014
     */
    public void setCodigoPersonaDe3(Integer codigoPersonaDe3) {
        this.codigoPersonaDe3 = codigoPersonaDe3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column informes.referencia
     *
     * @return the value of informes.referencia
     *
     * @mbggenerated Tue Mar 04 17:35:57 BOT 2014
     */
    public String getReferencia() {
        return referencia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column informes.referencia
     *
     * @param referencia the value for informes.referencia
     *
     * @mbggenerated Tue Mar 04 17:35:57 BOT 2014
     */
    public void setReferencia(String referencia) {
        this.referencia = referencia == null ? null : referencia.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column informes.fecha_registro
     *
     * @return the value of informes.fecha_registro
     *
     * @mbggenerated Tue Mar 04 17:35:57 BOT 2014
     */
    public Date getFechaRegistro() {
        return fechaRegistro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column informes.fecha_registro
     *
     * @param fechaRegistro the value for informes.fecha_registro
     *
     * @mbggenerated Tue Mar 04 17:35:57 BOT 2014
     */
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column informes.fecha_envio
     *
     * @return the value of informes.fecha_envio
     *
     * @mbggenerated Tue Mar 04 17:35:57 BOT 2014
     */
    public Date getFechaEnvio() {
        return fechaEnvio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column informes.fecha_envio
     *
     * @param fechaEnvio the value for informes.fecha_envio
     *
     * @mbggenerated Tue Mar 04 17:35:57 BOT 2014
     */
    public void setFechaEnvio(Date fechaEnvio) {
        this.fechaEnvio = fechaEnvio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column informes.diagnostico
     *
     * @return the value of informes.diagnostico
     *
     * @mbggenerated Tue Mar 04 17:35:57 BOT 2014
     */
    public String getDiagnostico() {
        return diagnostico;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column informes.diagnostico
     *
     * @param diagnostico the value for informes.diagnostico
     *
     * @mbggenerated Tue Mar 04 17:35:57 BOT 2014
     */
    public void setDiagnostico(String diagnostico) {
        this.diagnostico = diagnostico == null ? null : diagnostico.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column informes.sugerencias
     *
     * @return the value of informes.sugerencias
     *
     * @mbggenerated Tue Mar 04 17:35:57 BOT 2014
     */
    public String getSugerencias() {
        return sugerencias;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column informes.sugerencias
     *
     * @param sugerencias the value for informes.sugerencias
     *
     * @mbggenerated Tue Mar 04 17:35:57 BOT 2014
     */
    public void setSugerencias(String sugerencias) {
        this.sugerencias = sugerencias == null ? null : sugerencias.trim();
    }
    //"PSICOSOCIAL DE SEGUIMIENTO DE CONVIVENCIA", "PSICOSOCIAL DE SEGUIMIENTO", "INFORME SOCIAL", "INFORME SOCIAL DE SEGUIMIENTO", "FICHA SOCIAL"
	public String getTipo() {
		// TODO Auto-generated method stub
		switch (codigoTipoInforme) {
		case "A":
			return"PSICOSOCIAL DE SEGUIMIENTO DE CONVIVENCIA";
		case "B":
			return"PSICOSOCIAL DE SEGUIMIENTO";
		case "C":
			return"INFORME SOCIAL";
		case "D":
			return"INFORME SOCIAL DE SEGUIMIENTO";
		case "E":
			return"FICHA SOCIAL";

		default:
			return "";
		}
	}
	
	public void setTipo(String tipo)
	{
		switch (tipo) {
		case "PSICOSOCIAL DE SEGUIMIENTO DE CONVIVENCIA":
			codigoTipoInforme = "A";
			break;
		case "PSICOSOCIAL DE SEGUIMIENTO":
			codigoTipoInforme = "B";
			break;
		case "INFORME SOCIAL":
			codigoTipoInforme = "C";
			break;
		case "INFORME SOCIAL DE SEGUIMIENTO":
			codigoTipoInforme = "D";
			break;
		case "FICHA SOCIAL":
			codigoTipoInforme = "E";
			break;
		default:
			break;
		}
	}

	public Persona getNino() {
		return nino;
	}

	public void setNino(Persona nino) {
		this.nino = nino;
	}
}