package org.quarkbit.trabajosocialsanjuan.dao.domain;

import java.util.Date;

public class InformePsicologico {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column informe_psicologico.codigo_informe_psico
     *
     * @mbggenerated Sat Mar 29 13:41:55 BOT 2014
     */
    private Integer codigoInformePsicologico;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column informe_psicologico.codigo_kardex
     *
     * @mbggenerated Sat Mar 29 13:41:55 BOT 2014
     */
    private Integer codigoKardex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column informe_psicologico.motivo_consulta
     *
     * @mbggenerated Sat Mar 29 13:41:55 BOT 2014
     */
    private String motivoConsulta;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column informe_psicologico.fecha_evaluacion
     *
     * @mbggenerated Sat Mar 29 13:41:55 BOT 2014
     */
    private Date fechaEvaluacion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column informe_psicologico.codigo_persona_evalua
     *
     * @mbggenerated Sat Mar 29 13:41:55 BOT 2014
     */
    private Integer codigoPersonaEvaluadora;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column informe_psicologico.instrumentos
     *
     * @mbggenerated Sat Mar 29 13:41:55 BOT 2014
     */
    private String instrumentos;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column informe_psicologico.antecedentes
     *
     * @mbggenerated Sat Mar 29 13:41:55 BOT 2014
     */
    private String antecedentes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column informe_psicologico.aspectos_relevantes
     *
     * @mbggenerated Sat Mar 29 13:41:55 BOT 2014
     */
    private String aspectosRelevantes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column informe_psicologico.conductas_observadas
     *
     * @mbggenerated Sat Mar 29 13:41:55 BOT 2014
     */
    private String conductasObservadas;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column informe_psicologico.res_motricidad_gruesa
     *
     * @mbggenerated Sat Mar 29 13:41:55 BOT 2014
     */
    private String respuestaMotricidadGruesa;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column informe_psicologico.res_motricidad_fino
     *
     * @mbggenerated Sat Mar 29 13:41:55 BOT 2014
     */
    private String respuestaMotricidadFino;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column informe_psicologico.res_audicion_lenguaje
     *
     * @mbggenerated Sat Mar 29 13:41:55 BOT 2014
     */
    private String respuestaAudicionLenguaje;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column informe_psicologico.res_personal_social
     *
     * @mbggenerated Sat Mar 29 13:41:55 BOT 2014
     */
    private String respuestaPersonalSocial;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column informe_psicologico.res_total
     *
     * @mbggenerated Sat Mar 29 13:41:55 BOT 2014
     */
    private String respuestaTotal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column informe_psicologico.diagnostico
     *
     * @mbggenerated Sat Mar 29 13:41:55 BOT 2014
     */
    private String diagnostico;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column informe_psicologico.recomendaciones
     *
     * @mbggenerated Sat Mar 29 13:41:55 BOT 2014
     */
    private String recomendaciones;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column informe_psicologico.codigo_informe_psico
     *
     * @return the value of informe_psicologico.codigo_informe_psico
     *
     * @mbggenerated Sat Mar 29 13:41:55 BOT 2014
     */
    public Integer getCodigoInformePsicologico() {
        return codigoInformePsicologico;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column informe_psicologico.codigo_informe_psico
     *
     * @param codigoInformePsicologico the value for informe_psicologico.codigo_informe_psico
     *
     * @mbggenerated Sat Mar 29 13:41:55 BOT 2014
     */
    public void setCodigoInformePsicologico(Integer codigoInformePsicologico) {
        this.codigoInformePsicologico = codigoInformePsicologico;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column informe_psicologico.codigo_kardex
     *
     * @return the value of informe_psicologico.codigo_kardex
     *
     * @mbggenerated Sat Mar 29 13:41:55 BOT 2014
     */
    public Integer getCodigoKardex() {
        return codigoKardex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column informe_psicologico.codigo_kardex
     *
     * @param codigoKardex the value for informe_psicologico.codigo_kardex
     *
     * @mbggenerated Sat Mar 29 13:41:55 BOT 2014
     */
    public void setCodigoKardex(Integer codigoKardex) {
        this.codigoKardex = codigoKardex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column informe_psicologico.motivo_consulta
     *
     * @return the value of informe_psicologico.motivo_consulta
     *
     * @mbggenerated Sat Mar 29 13:41:55 BOT 2014
     */
    public String getMotivoConsulta() {
        return motivoConsulta;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column informe_psicologico.motivo_consulta
     *
     * @param motivoConsulta the value for informe_psicologico.motivo_consulta
     *
     * @mbggenerated Sat Mar 29 13:41:55 BOT 2014
     */
    public void setMotivoConsulta(String motivoConsulta) {
        this.motivoConsulta = motivoConsulta == null ? null : motivoConsulta.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column informe_psicologico.fecha_evaluacion
     *
     * @return the value of informe_psicologico.fecha_evaluacion
     *
     * @mbggenerated Sat Mar 29 13:41:55 BOT 2014
     */
    public Date getFechaEvaluacion() {
        return fechaEvaluacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column informe_psicologico.fecha_evaluacion
     *
     * @param fechaEvaluacion the value for informe_psicologico.fecha_evaluacion
     *
     * @mbggenerated Sat Mar 29 13:41:55 BOT 2014
     */
    public void setFechaEvaluacion(Date fechaEvaluacion) {
        this.fechaEvaluacion = fechaEvaluacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column informe_psicologico.codigo_persona_evalua
     *
     * @return the value of informe_psicologico.codigo_persona_evalua
     *
     * @mbggenerated Sat Mar 29 13:41:55 BOT 2014
     */
    public Integer getCodigoPersonaEvaluadora() {
        return codigoPersonaEvaluadora;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column informe_psicologico.codigo_persona_evalua
     *
     * @param codigoPersonaEvaluadora the value for informe_psicologico.codigo_persona_evalua
     *
     * @mbggenerated Sat Mar 29 13:41:55 BOT 2014
     */
    public void setCodigoPersonaEvaluadora(Integer codigoPersonaEvaluadora) {
        this.codigoPersonaEvaluadora = codigoPersonaEvaluadora;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column informe_psicologico.instrumentos
     *
     * @return the value of informe_psicologico.instrumentos
     *
     * @mbggenerated Sat Mar 29 13:41:55 BOT 2014
     */
    public String getInstrumentos() {
        return instrumentos;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column informe_psicologico.instrumentos
     *
     * @param instrumentos the value for informe_psicologico.instrumentos
     *
     * @mbggenerated Sat Mar 29 13:41:55 BOT 2014
     */
    public void setInstrumentos(String instrumentos) {
        this.instrumentos = instrumentos == null ? null : instrumentos.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column informe_psicologico.antecedentes
     *
     * @return the value of informe_psicologico.antecedentes
     *
     * @mbggenerated Sat Mar 29 13:41:55 BOT 2014
     */
    public String getAntecedentes() {
        return antecedentes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column informe_psicologico.antecedentes
     *
     * @param antecedentes the value for informe_psicologico.antecedentes
     *
     * @mbggenerated Sat Mar 29 13:41:55 BOT 2014
     */
    public void setAntecedentes(String antecedentes) {
        this.antecedentes = antecedentes == null ? null : antecedentes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column informe_psicologico.aspectos_relevantes
     *
     * @return the value of informe_psicologico.aspectos_relevantes
     *
     * @mbggenerated Sat Mar 29 13:41:55 BOT 2014
     */
    public String getAspectosRelevantes() {
        return aspectosRelevantes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column informe_psicologico.aspectos_relevantes
     *
     * @param aspectosRelevantes the value for informe_psicologico.aspectos_relevantes
     *
     * @mbggenerated Sat Mar 29 13:41:55 BOT 2014
     */
    public void setAspectosRelevantes(String aspectosRelevantes) {
        this.aspectosRelevantes = aspectosRelevantes == null ? null : aspectosRelevantes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column informe_psicologico.conductas_observadas
     *
     * @return the value of informe_psicologico.conductas_observadas
     *
     * @mbggenerated Sat Mar 29 13:41:55 BOT 2014
     */
    public String getConductasObservadas() {
        return conductasObservadas;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column informe_psicologico.conductas_observadas
     *
     * @param conductasObservadas the value for informe_psicologico.conductas_observadas
     *
     * @mbggenerated Sat Mar 29 13:41:55 BOT 2014
     */
    public void setConductasObservadas(String conductasObservadas) {
        this.conductasObservadas = conductasObservadas == null ? null : conductasObservadas.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column informe_psicologico.res_motricidad_gruesa
     *
     * @return the value of informe_psicologico.res_motricidad_gruesa
     *
     * @mbggenerated Sat Mar 29 13:41:55 BOT 2014
     */
    public String getRespuestaMotricidadGruesa() {
        return respuestaMotricidadGruesa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column informe_psicologico.res_motricidad_gruesa
     *
     * @param respuestaMotricidadGruesa the value for informe_psicologico.res_motricidad_gruesa
     *
     * @mbggenerated Sat Mar 29 13:41:55 BOT 2014
     */
    public void setRespuestaMotricidadGruesa(String respuestaMotricidadGruesa) {
        this.respuestaMotricidadGruesa = respuestaMotricidadGruesa == null ? null : respuestaMotricidadGruesa.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column informe_psicologico.res_motricidad_fino
     *
     * @return the value of informe_psicologico.res_motricidad_fino
     *
     * @mbggenerated Sat Mar 29 13:41:55 BOT 2014
     */
    public String getRespuestaMotricidadFino() {
        return respuestaMotricidadFino;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column informe_psicologico.res_motricidad_fino
     *
     * @param respuestaMotricidadFino the value for informe_psicologico.res_motricidad_fino
     *
     * @mbggenerated Sat Mar 29 13:41:55 BOT 2014
     */
    public void setRespuestaMotricidadFino(String respuestaMotricidadFino) {
        this.respuestaMotricidadFino = respuestaMotricidadFino == null ? null : respuestaMotricidadFino.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column informe_psicologico.res_audicion_lenguaje
     *
     * @return the value of informe_psicologico.res_audicion_lenguaje
     *
     * @mbggenerated Sat Mar 29 13:41:55 BOT 2014
     */
    public String getRespuestaAudicionLenguaje() {
        return respuestaAudicionLenguaje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column informe_psicologico.res_audicion_lenguaje
     *
     * @param respuestaAudicionLenguaje the value for informe_psicologico.res_audicion_lenguaje
     *
     * @mbggenerated Sat Mar 29 13:41:55 BOT 2014
     */
    public void setRespuestaAudicionLenguaje(String respuestaAudicionLenguaje) {
        this.respuestaAudicionLenguaje = respuestaAudicionLenguaje == null ? null : respuestaAudicionLenguaje.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column informe_psicologico.res_personal_social
     *
     * @return the value of informe_psicologico.res_personal_social
     *
     * @mbggenerated Sat Mar 29 13:41:55 BOT 2014
     */
    public String getRespuestaPersonalSocial() {
        return respuestaPersonalSocial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column informe_psicologico.res_personal_social
     *
     * @param respuestaPersonalSocial the value for informe_psicologico.res_personal_social
     *
     * @mbggenerated Sat Mar 29 13:41:55 BOT 2014
     */
    public void setRespuestaPersonalSocial(String respuestaPersonalSocial) {
        this.respuestaPersonalSocial = respuestaPersonalSocial == null ? null : respuestaPersonalSocial.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column informe_psicologico.res_total
     *
     * @return the value of informe_psicologico.res_total
     *
     * @mbggenerated Sat Mar 29 13:41:55 BOT 2014
     */
    public String getRespuestaTotal() {
        return respuestaTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column informe_psicologico.res_total
     *
     * @param respuestaTotal the value for informe_psicologico.res_total
     *
     * @mbggenerated Sat Mar 29 13:41:55 BOT 2014
     */
    public void setRespuestaTotal(String respuestaTotal) {
        this.respuestaTotal = respuestaTotal == null ? null : respuestaTotal.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column informe_psicologico.diagnostico
     *
     * @return the value of informe_psicologico.diagnostico
     *
     * @mbggenerated Sat Mar 29 13:41:55 BOT 2014
     */
    public String getDiagnostico() {
        return diagnostico;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column informe_psicologico.diagnostico
     *
     * @param diagnostico the value for informe_psicologico.diagnostico
     *
     * @mbggenerated Sat Mar 29 13:41:55 BOT 2014
     */
    public void setDiagnostico(String diagnostico) {
        this.diagnostico = diagnostico == null ? null : diagnostico.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column informe_psicologico.recomendaciones
     *
     * @return the value of informe_psicologico.recomendaciones
     *
     * @mbggenerated Sat Mar 29 13:41:55 BOT 2014
     */
    public String getRecomendaciones() {
        return recomendaciones;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column informe_psicologico.recomendaciones
     *
     * @param recomendaciones the value for informe_psicologico.recomendaciones
     *
     * @mbggenerated Sat Mar 29 13:41:55 BOT 2014
     */
    public void setRecomendaciones(String recomendaciones) {
        this.recomendaciones = recomendaciones == null ? null : recomendaciones.trim();
    }
}