package org.quarkbit.trabajosocialsanjuan.dao.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class InformePsicologicoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table informe_psicologico
     *
     * @mbggenerated Sat Mar 29 13:41:55 BOT 2014
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table informe_psicologico
     *
     * @mbggenerated Sat Mar 29 13:41:55 BOT 2014
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table informe_psicologico
     *
     * @mbggenerated Sat Mar 29 13:41:55 BOT 2014
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table informe_psicologico
     *
     * @mbggenerated Sat Mar 29 13:41:55 BOT 2014
     */
    public InformePsicologicoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table informe_psicologico
     *
     * @mbggenerated Sat Mar 29 13:41:55 BOT 2014
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table informe_psicologico
     *
     * @mbggenerated Sat Mar 29 13:41:55 BOT 2014
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table informe_psicologico
     *
     * @mbggenerated Sat Mar 29 13:41:55 BOT 2014
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table informe_psicologico
     *
     * @mbggenerated Sat Mar 29 13:41:55 BOT 2014
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table informe_psicologico
     *
     * @mbggenerated Sat Mar 29 13:41:55 BOT 2014
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table informe_psicologico
     *
     * @mbggenerated Sat Mar 29 13:41:55 BOT 2014
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table informe_psicologico
     *
     * @mbggenerated Sat Mar 29 13:41:55 BOT 2014
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table informe_psicologico
     *
     * @mbggenerated Sat Mar 29 13:41:55 BOT 2014
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table informe_psicologico
     *
     * @mbggenerated Sat Mar 29 13:41:55 BOT 2014
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table informe_psicologico
     *
     * @mbggenerated Sat Mar 29 13:41:55 BOT 2014
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table informe_psicologico
     *
     * @mbggenerated Sat Mar 29 13:41:55 BOT 2014
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andCodigoInformePsicologicoIsNull() {
            addCriterion("codigo_informe_psico is null");
            return (Criteria) this;
        }

        public Criteria andCodigoInformePsicologicoIsNotNull() {
            addCriterion("codigo_informe_psico is not null");
            return (Criteria) this;
        }

        public Criteria andCodigoInformePsicologicoEqualTo(Integer value) {
            addCriterion("codigo_informe_psico =", value, "codigoInformePsicologico");
            return (Criteria) this;
        }

        public Criteria andCodigoInformePsicologicoNotEqualTo(Integer value) {
            addCriterion("codigo_informe_psico <>", value, "codigoInformePsicologico");
            return (Criteria) this;
        }

        public Criteria andCodigoInformePsicologicoGreaterThan(Integer value) {
            addCriterion("codigo_informe_psico >", value, "codigoInformePsicologico");
            return (Criteria) this;
        }

        public Criteria andCodigoInformePsicologicoGreaterThanOrEqualTo(Integer value) {
            addCriterion("codigo_informe_psico >=", value, "codigoInformePsicologico");
            return (Criteria) this;
        }

        public Criteria andCodigoInformePsicologicoLessThan(Integer value) {
            addCriterion("codigo_informe_psico <", value, "codigoInformePsicologico");
            return (Criteria) this;
        }

        public Criteria andCodigoInformePsicologicoLessThanOrEqualTo(Integer value) {
            addCriterion("codigo_informe_psico <=", value, "codigoInformePsicologico");
            return (Criteria) this;
        }

        public Criteria andCodigoInformePsicologicoIn(List<Integer> values) {
            addCriterion("codigo_informe_psico in", values, "codigoInformePsicologico");
            return (Criteria) this;
        }

        public Criteria andCodigoInformePsicologicoNotIn(List<Integer> values) {
            addCriterion("codigo_informe_psico not in", values, "codigoInformePsicologico");
            return (Criteria) this;
        }

        public Criteria andCodigoInformePsicologicoBetween(Integer value1, Integer value2) {
            addCriterion("codigo_informe_psico between", value1, value2, "codigoInformePsicologico");
            return (Criteria) this;
        }

        public Criteria andCodigoInformePsicologicoNotBetween(Integer value1, Integer value2) {
            addCriterion("codigo_informe_psico not between", value1, value2, "codigoInformePsicologico");
            return (Criteria) this;
        }

        public Criteria andCodigoKardexIsNull() {
            addCriterion("codigo_kardex is null");
            return (Criteria) this;
        }

        public Criteria andCodigoKardexIsNotNull() {
            addCriterion("codigo_kardex is not null");
            return (Criteria) this;
        }

        public Criteria andCodigoKardexEqualTo(Integer value) {
            addCriterion("codigo_kardex =", value, "codigoKardex");
            return (Criteria) this;
        }

        public Criteria andCodigoKardexNotEqualTo(Integer value) {
            addCriterion("codigo_kardex <>", value, "codigoKardex");
            return (Criteria) this;
        }

        public Criteria andCodigoKardexGreaterThan(Integer value) {
            addCriterion("codigo_kardex >", value, "codigoKardex");
            return (Criteria) this;
        }

        public Criteria andCodigoKardexGreaterThanOrEqualTo(Integer value) {
            addCriterion("codigo_kardex >=", value, "codigoKardex");
            return (Criteria) this;
        }

        public Criteria andCodigoKardexLessThan(Integer value) {
            addCriterion("codigo_kardex <", value, "codigoKardex");
            return (Criteria) this;
        }

        public Criteria andCodigoKardexLessThanOrEqualTo(Integer value) {
            addCriterion("codigo_kardex <=", value, "codigoKardex");
            return (Criteria) this;
        }

        public Criteria andCodigoKardexIn(List<Integer> values) {
            addCriterion("codigo_kardex in", values, "codigoKardex");
            return (Criteria) this;
        }

        public Criteria andCodigoKardexNotIn(List<Integer> values) {
            addCriterion("codigo_kardex not in", values, "codigoKardex");
            return (Criteria) this;
        }

        public Criteria andCodigoKardexBetween(Integer value1, Integer value2) {
            addCriterion("codigo_kardex between", value1, value2, "codigoKardex");
            return (Criteria) this;
        }

        public Criteria andCodigoKardexNotBetween(Integer value1, Integer value2) {
            addCriterion("codigo_kardex not between", value1, value2, "codigoKardex");
            return (Criteria) this;
        }

        public Criteria andMotivoConsultaIsNull() {
            addCriterion("motivo_consulta is null");
            return (Criteria) this;
        }

        public Criteria andMotivoConsultaIsNotNull() {
            addCriterion("motivo_consulta is not null");
            return (Criteria) this;
        }

        public Criteria andMotivoConsultaEqualTo(String value) {
            addCriterion("motivo_consulta =", value, "motivoConsulta");
            return (Criteria) this;
        }

        public Criteria andMotivoConsultaNotEqualTo(String value) {
            addCriterion("motivo_consulta <>", value, "motivoConsulta");
            return (Criteria) this;
        }

        public Criteria andMotivoConsultaGreaterThan(String value) {
            addCriterion("motivo_consulta >", value, "motivoConsulta");
            return (Criteria) this;
        }

        public Criteria andMotivoConsultaGreaterThanOrEqualTo(String value) {
            addCriterion("motivo_consulta >=", value, "motivoConsulta");
            return (Criteria) this;
        }

        public Criteria andMotivoConsultaLessThan(String value) {
            addCriterion("motivo_consulta <", value, "motivoConsulta");
            return (Criteria) this;
        }

        public Criteria andMotivoConsultaLessThanOrEqualTo(String value) {
            addCriterion("motivo_consulta <=", value, "motivoConsulta");
            return (Criteria) this;
        }

        public Criteria andMotivoConsultaLike(String value) {
            addCriterion("upper(motivo_consulta) like", value, "motivoConsulta");
            return (Criteria) this;
        }

        public Criteria andMotivoConsultaNotLike(String value) {
            addCriterion("motivo_consulta not like", value, "motivoConsulta");
            return (Criteria) this;
        }

        public Criteria andMotivoConsultaIn(List<String> values) {
            addCriterion("motivo_consulta in", values, "motivoConsulta");
            return (Criteria) this;
        }

        public Criteria andMotivoConsultaNotIn(List<String> values) {
            addCriterion("motivo_consulta not in", values, "motivoConsulta");
            return (Criteria) this;
        }

        public Criteria andMotivoConsultaBetween(String value1, String value2) {
            addCriterion("motivo_consulta between", value1, value2, "motivoConsulta");
            return (Criteria) this;
        }

        public Criteria andMotivoConsultaNotBetween(String value1, String value2) {
            addCriterion("motivo_consulta not between", value1, value2, "motivoConsulta");
            return (Criteria) this;
        }

        public Criteria andFechaEvaluacionIsNull() {
            addCriterion("fecha_evaluacion is null");
            return (Criteria) this;
        }

        public Criteria andFechaEvaluacionIsNotNull() {
            addCriterion("fecha_evaluacion is not null");
            return (Criteria) this;
        }

        public Criteria andFechaEvaluacionEqualTo(Date value) {
            addCriterionForJDBCDate("fecha_evaluacion =", value, "fechaEvaluacion");
            return (Criteria) this;
        }

        public Criteria andFechaEvaluacionNotEqualTo(Date value) {
            addCriterionForJDBCDate("fecha_evaluacion <>", value, "fechaEvaluacion");
            return (Criteria) this;
        }

        public Criteria andFechaEvaluacionGreaterThan(Date value) {
            addCriterionForJDBCDate("fecha_evaluacion >", value, "fechaEvaluacion");
            return (Criteria) this;
        }

        public Criteria andFechaEvaluacionGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("fecha_evaluacion >=", value, "fechaEvaluacion");
            return (Criteria) this;
        }

        public Criteria andFechaEvaluacionLessThan(Date value) {
            addCriterionForJDBCDate("fecha_evaluacion <", value, "fechaEvaluacion");
            return (Criteria) this;
        }

        public Criteria andFechaEvaluacionLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("fecha_evaluacion <=", value, "fechaEvaluacion");
            return (Criteria) this;
        }

        public Criteria andFechaEvaluacionIn(List<Date> values) {
            addCriterionForJDBCDate("fecha_evaluacion in", values, "fechaEvaluacion");
            return (Criteria) this;
        }

        public Criteria andFechaEvaluacionNotIn(List<Date> values) {
            addCriterionForJDBCDate("fecha_evaluacion not in", values, "fechaEvaluacion");
            return (Criteria) this;
        }

        public Criteria andFechaEvaluacionBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("fecha_evaluacion between", value1, value2, "fechaEvaluacion");
            return (Criteria) this;
        }

        public Criteria andFechaEvaluacionNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("fecha_evaluacion not between", value1, value2, "fechaEvaluacion");
            return (Criteria) this;
        }

        public Criteria andCodigoPersonaEvaluadoraIsNull() {
            addCriterion("codigo_persona_evalua is null");
            return (Criteria) this;
        }

        public Criteria andCodigoPersonaEvaluadoraIsNotNull() {
            addCriterion("codigo_persona_evalua is not null");
            return (Criteria) this;
        }

        public Criteria andCodigoPersonaEvaluadoraEqualTo(Integer value) {
            addCriterion("codigo_persona_evalua =", value, "codigoPersonaEvaluadora");
            return (Criteria) this;
        }

        public Criteria andCodigoPersonaEvaluadoraNotEqualTo(Integer value) {
            addCriterion("codigo_persona_evalua <>", value, "codigoPersonaEvaluadora");
            return (Criteria) this;
        }

        public Criteria andCodigoPersonaEvaluadoraGreaterThan(Integer value) {
            addCriterion("codigo_persona_evalua >", value, "codigoPersonaEvaluadora");
            return (Criteria) this;
        }

        public Criteria andCodigoPersonaEvaluadoraGreaterThanOrEqualTo(Integer value) {
            addCriterion("codigo_persona_evalua >=", value, "codigoPersonaEvaluadora");
            return (Criteria) this;
        }

        public Criteria andCodigoPersonaEvaluadoraLessThan(Integer value) {
            addCriterion("codigo_persona_evalua <", value, "codigoPersonaEvaluadora");
            return (Criteria) this;
        }

        public Criteria andCodigoPersonaEvaluadoraLessThanOrEqualTo(Integer value) {
            addCriterion("codigo_persona_evalua <=", value, "codigoPersonaEvaluadora");
            return (Criteria) this;
        }

        public Criteria andCodigoPersonaEvaluadoraIn(List<Integer> values) {
            addCriterion("codigo_persona_evalua in", values, "codigoPersonaEvaluadora");
            return (Criteria) this;
        }

        public Criteria andCodigoPersonaEvaluadoraNotIn(List<Integer> values) {
            addCriterion("codigo_persona_evalua not in", values, "codigoPersonaEvaluadora");
            return (Criteria) this;
        }

        public Criteria andCodigoPersonaEvaluadoraBetween(Integer value1, Integer value2) {
            addCriterion("codigo_persona_evalua between", value1, value2, "codigoPersonaEvaluadora");
            return (Criteria) this;
        }

        public Criteria andCodigoPersonaEvaluadoraNotBetween(Integer value1, Integer value2) {
            addCriterion("codigo_persona_evalua not between", value1, value2, "codigoPersonaEvaluadora");
            return (Criteria) this;
        }

        public Criteria andInstrumentosIsNull() {
            addCriterion("instrumentos is null");
            return (Criteria) this;
        }

        public Criteria andInstrumentosIsNotNull() {
            addCriterion("instrumentos is not null");
            return (Criteria) this;
        }

        public Criteria andInstrumentosEqualTo(String value) {
            addCriterion("instrumentos =", value, "instrumentos");
            return (Criteria) this;
        }

        public Criteria andInstrumentosNotEqualTo(String value) {
            addCriterion("instrumentos <>", value, "instrumentos");
            return (Criteria) this;
        }

        public Criteria andInstrumentosGreaterThan(String value) {
            addCriterion("instrumentos >", value, "instrumentos");
            return (Criteria) this;
        }

        public Criteria andInstrumentosGreaterThanOrEqualTo(String value) {
            addCriterion("instrumentos >=", value, "instrumentos");
            return (Criteria) this;
        }

        public Criteria andInstrumentosLessThan(String value) {
            addCriterion("instrumentos <", value, "instrumentos");
            return (Criteria) this;
        }

        public Criteria andInstrumentosLessThanOrEqualTo(String value) {
            addCriterion("instrumentos <=", value, "instrumentos");
            return (Criteria) this;
        }

        public Criteria andInstrumentosLike(String value) {
            addCriterion("instrumentos like", value, "instrumentos");
            return (Criteria) this;
        }

        public Criteria andInstrumentosNotLike(String value) {
            addCriterion("instrumentos not like", value, "instrumentos");
            return (Criteria) this;
        }

        public Criteria andInstrumentosIn(List<String> values) {
            addCriterion("instrumentos in", values, "instrumentos");
            return (Criteria) this;
        }

        public Criteria andInstrumentosNotIn(List<String> values) {
            addCriterion("instrumentos not in", values, "instrumentos");
            return (Criteria) this;
        }

        public Criteria andInstrumentosBetween(String value1, String value2) {
            addCriterion("instrumentos between", value1, value2, "instrumentos");
            return (Criteria) this;
        }

        public Criteria andInstrumentosNotBetween(String value1, String value2) {
            addCriterion("instrumentos not between", value1, value2, "instrumentos");
            return (Criteria) this;
        }

        public Criteria andAntecedentesIsNull() {
            addCriterion("antecedentes is null");
            return (Criteria) this;
        }

        public Criteria andAntecedentesIsNotNull() {
            addCriterion("antecedentes is not null");
            return (Criteria) this;
        }

        public Criteria andAntecedentesEqualTo(String value) {
            addCriterion("antecedentes =", value, "antecedentes");
            return (Criteria) this;
        }

        public Criteria andAntecedentesNotEqualTo(String value) {
            addCriterion("antecedentes <>", value, "antecedentes");
            return (Criteria) this;
        }

        public Criteria andAntecedentesGreaterThan(String value) {
            addCriterion("antecedentes >", value, "antecedentes");
            return (Criteria) this;
        }

        public Criteria andAntecedentesGreaterThanOrEqualTo(String value) {
            addCriterion("antecedentes >=", value, "antecedentes");
            return (Criteria) this;
        }

        public Criteria andAntecedentesLessThan(String value) {
            addCriterion("antecedentes <", value, "antecedentes");
            return (Criteria) this;
        }

        public Criteria andAntecedentesLessThanOrEqualTo(String value) {
            addCriterion("antecedentes <=", value, "antecedentes");
            return (Criteria) this;
        }

        public Criteria andAntecedentesLike(String value) {
            addCriterion("upper(antecedentes) like", value, "antecedentes");
            return (Criteria) this;
        }

        public Criteria andAntecedentesNotLike(String value) {
            addCriterion("antecedentes not like", value, "antecedentes");
            return (Criteria) this;
        }

        public Criteria andAntecedentesIn(List<String> values) {
            addCriterion("antecedentes in", values, "antecedentes");
            return (Criteria) this;
        }

        public Criteria andAntecedentesNotIn(List<String> values) {
            addCriterion("antecedentes not in", values, "antecedentes");
            return (Criteria) this;
        }

        public Criteria andAntecedentesBetween(String value1, String value2) {
            addCriterion("antecedentes between", value1, value2, "antecedentes");
            return (Criteria) this;
        }

        public Criteria andAntecedentesNotBetween(String value1, String value2) {
            addCriterion("antecedentes not between", value1, value2, "antecedentes");
            return (Criteria) this;
        }

        public Criteria andAspectosRelevantesIsNull() {
            addCriterion("aspectos_relevantes is null");
            return (Criteria) this;
        }

        public Criteria andAspectosRelevantesIsNotNull() {
            addCriterion("aspectos_relevantes is not null");
            return (Criteria) this;
        }

        public Criteria andAspectosRelevantesEqualTo(String value) {
            addCriterion("aspectos_relevantes =", value, "aspectosRelevantes");
            return (Criteria) this;
        }

        public Criteria andAspectosRelevantesNotEqualTo(String value) {
            addCriterion("aspectos_relevantes <>", value, "aspectosRelevantes");
            return (Criteria) this;
        }

        public Criteria andAspectosRelevantesGreaterThan(String value) {
            addCriterion("aspectos_relevantes >", value, "aspectosRelevantes");
            return (Criteria) this;
        }

        public Criteria andAspectosRelevantesGreaterThanOrEqualTo(String value) {
            addCriterion("aspectos_relevantes >=", value, "aspectosRelevantes");
            return (Criteria) this;
        }

        public Criteria andAspectosRelevantesLessThan(String value) {
            addCriterion("aspectos_relevantes <", value, "aspectosRelevantes");
            return (Criteria) this;
        }

        public Criteria andAspectosRelevantesLessThanOrEqualTo(String value) {
            addCriterion("aspectos_relevantes <=", value, "aspectosRelevantes");
            return (Criteria) this;
        }

        public Criteria andAspectosRelevantesLike(String value) {
            addCriterion("aspectos_relevantes like", value, "aspectosRelevantes");
            return (Criteria) this;
        }

        public Criteria andAspectosRelevantesNotLike(String value) {
            addCriterion("aspectos_relevantes not like", value, "aspectosRelevantes");
            return (Criteria) this;
        }

        public Criteria andAspectosRelevantesIn(List<String> values) {
            addCriterion("aspectos_relevantes in", values, "aspectosRelevantes");
            return (Criteria) this;
        }

        public Criteria andAspectosRelevantesNotIn(List<String> values) {
            addCriterion("aspectos_relevantes not in", values, "aspectosRelevantes");
            return (Criteria) this;
        }

        public Criteria andAspectosRelevantesBetween(String value1, String value2) {
            addCriterion("aspectos_relevantes between", value1, value2, "aspectosRelevantes");
            return (Criteria) this;
        }

        public Criteria andAspectosRelevantesNotBetween(String value1, String value2) {
            addCriterion("aspectos_relevantes not between", value1, value2, "aspectosRelevantes");
            return (Criteria) this;
        }

        public Criteria andConductasObservadasIsNull() {
            addCriterion("conductas_observadas is null");
            return (Criteria) this;
        }

        public Criteria andConductasObservadasIsNotNull() {
            addCriterion("conductas_observadas is not null");
            return (Criteria) this;
        }

        public Criteria andConductasObservadasEqualTo(String value) {
            addCriterion("conductas_observadas =", value, "conductasObservadas");
            return (Criteria) this;
        }

        public Criteria andConductasObservadasNotEqualTo(String value) {
            addCriterion("conductas_observadas <>", value, "conductasObservadas");
            return (Criteria) this;
        }

        public Criteria andConductasObservadasGreaterThan(String value) {
            addCriterion("conductas_observadas >", value, "conductasObservadas");
            return (Criteria) this;
        }

        public Criteria andConductasObservadasGreaterThanOrEqualTo(String value) {
            addCriterion("conductas_observadas >=", value, "conductasObservadas");
            return (Criteria) this;
        }

        public Criteria andConductasObservadasLessThan(String value) {
            addCriterion("conductas_observadas <", value, "conductasObservadas");
            return (Criteria) this;
        }

        public Criteria andConductasObservadasLessThanOrEqualTo(String value) {
            addCriterion("conductas_observadas <=", value, "conductasObservadas");
            return (Criteria) this;
        }

        public Criteria andConductasObservadasLike(String value) {
            addCriterion("conductas_observadas like", value, "conductasObservadas");
            return (Criteria) this;
        }

        public Criteria andConductasObservadasNotLike(String value) {
            addCriterion("conductas_observadas not like", value, "conductasObservadas");
            return (Criteria) this;
        }

        public Criteria andConductasObservadasIn(List<String> values) {
            addCriterion("conductas_observadas in", values, "conductasObservadas");
            return (Criteria) this;
        }

        public Criteria andConductasObservadasNotIn(List<String> values) {
            addCriterion("conductas_observadas not in", values, "conductasObservadas");
            return (Criteria) this;
        }

        public Criteria andConductasObservadasBetween(String value1, String value2) {
            addCriterion("conductas_observadas between", value1, value2, "conductasObservadas");
            return (Criteria) this;
        }

        public Criteria andConductasObservadasNotBetween(String value1, String value2) {
            addCriterion("conductas_observadas not between", value1, value2, "conductasObservadas");
            return (Criteria) this;
        }

        public Criteria andRespuestaMotricidadGruesaIsNull() {
            addCriterion("res_motricidad_gruesa is null");
            return (Criteria) this;
        }

        public Criteria andRespuestaMotricidadGruesaIsNotNull() {
            addCriterion("res_motricidad_gruesa is not null");
            return (Criteria) this;
        }

        public Criteria andRespuestaMotricidadGruesaEqualTo(String value) {
            addCriterion("res_motricidad_gruesa =", value, "respuestaMotricidadGruesa");
            return (Criteria) this;
        }

        public Criteria andRespuestaMotricidadGruesaNotEqualTo(String value) {
            addCriterion("res_motricidad_gruesa <>", value, "respuestaMotricidadGruesa");
            return (Criteria) this;
        }

        public Criteria andRespuestaMotricidadGruesaGreaterThan(String value) {
            addCriterion("res_motricidad_gruesa >", value, "respuestaMotricidadGruesa");
            return (Criteria) this;
        }

        public Criteria andRespuestaMotricidadGruesaGreaterThanOrEqualTo(String value) {
            addCriterion("res_motricidad_gruesa >=", value, "respuestaMotricidadGruesa");
            return (Criteria) this;
        }

        public Criteria andRespuestaMotricidadGruesaLessThan(String value) {
            addCriterion("res_motricidad_gruesa <", value, "respuestaMotricidadGruesa");
            return (Criteria) this;
        }

        public Criteria andRespuestaMotricidadGruesaLessThanOrEqualTo(String value) {
            addCriterion("res_motricidad_gruesa <=", value, "respuestaMotricidadGruesa");
            return (Criteria) this;
        }

        public Criteria andRespuestaMotricidadGruesaLike(String value) {
            addCriterion("res_motricidad_gruesa like", value, "respuestaMotricidadGruesa");
            return (Criteria) this;
        }

        public Criteria andRespuestaMotricidadGruesaNotLike(String value) {
            addCriterion("res_motricidad_gruesa not like", value, "respuestaMotricidadGruesa");
            return (Criteria) this;
        }

        public Criteria andRespuestaMotricidadGruesaIn(List<String> values) {
            addCriterion("res_motricidad_gruesa in", values, "respuestaMotricidadGruesa");
            return (Criteria) this;
        }

        public Criteria andRespuestaMotricidadGruesaNotIn(List<String> values) {
            addCriterion("res_motricidad_gruesa not in", values, "respuestaMotricidadGruesa");
            return (Criteria) this;
        }

        public Criteria andRespuestaMotricidadGruesaBetween(String value1, String value2) {
            addCriterion("res_motricidad_gruesa between", value1, value2, "respuestaMotricidadGruesa");
            return (Criteria) this;
        }

        public Criteria andRespuestaMotricidadGruesaNotBetween(String value1, String value2) {
            addCriterion("res_motricidad_gruesa not between", value1, value2, "respuestaMotricidadGruesa");
            return (Criteria) this;
        }

        public Criteria andRespuestaMotricidadFinoIsNull() {
            addCriterion("res_motricidad_fino is null");
            return (Criteria) this;
        }

        public Criteria andRespuestaMotricidadFinoIsNotNull() {
            addCriterion("res_motricidad_fino is not null");
            return (Criteria) this;
        }

        public Criteria andRespuestaMotricidadFinoEqualTo(String value) {
            addCriterion("res_motricidad_fino =", value, "respuestaMotricidadFino");
            return (Criteria) this;
        }

        public Criteria andRespuestaMotricidadFinoNotEqualTo(String value) {
            addCriterion("res_motricidad_fino <>", value, "respuestaMotricidadFino");
            return (Criteria) this;
        }

        public Criteria andRespuestaMotricidadFinoGreaterThan(String value) {
            addCriterion("res_motricidad_fino >", value, "respuestaMotricidadFino");
            return (Criteria) this;
        }

        public Criteria andRespuestaMotricidadFinoGreaterThanOrEqualTo(String value) {
            addCriterion("res_motricidad_fino >=", value, "respuestaMotricidadFino");
            return (Criteria) this;
        }

        public Criteria andRespuestaMotricidadFinoLessThan(String value) {
            addCriterion("res_motricidad_fino <", value, "respuestaMotricidadFino");
            return (Criteria) this;
        }

        public Criteria andRespuestaMotricidadFinoLessThanOrEqualTo(String value) {
            addCriterion("res_motricidad_fino <=", value, "respuestaMotricidadFino");
            return (Criteria) this;
        }

        public Criteria andRespuestaMotricidadFinoLike(String value) {
            addCriterion("res_motricidad_fino like", value, "respuestaMotricidadFino");
            return (Criteria) this;
        }

        public Criteria andRespuestaMotricidadFinoNotLike(String value) {
            addCriterion("res_motricidad_fino not like", value, "respuestaMotricidadFino");
            return (Criteria) this;
        }

        public Criteria andRespuestaMotricidadFinoIn(List<String> values) {
            addCriterion("res_motricidad_fino in", values, "respuestaMotricidadFino");
            return (Criteria) this;
        }

        public Criteria andRespuestaMotricidadFinoNotIn(List<String> values) {
            addCriterion("res_motricidad_fino not in", values, "respuestaMotricidadFino");
            return (Criteria) this;
        }

        public Criteria andRespuestaMotricidadFinoBetween(String value1, String value2) {
            addCriterion("res_motricidad_fino between", value1, value2, "respuestaMotricidadFino");
            return (Criteria) this;
        }

        public Criteria andRespuestaMotricidadFinoNotBetween(String value1, String value2) {
            addCriterion("res_motricidad_fino not between", value1, value2, "respuestaMotricidadFino");
            return (Criteria) this;
        }

        public Criteria andRespuestaAudicionLenguajeIsNull() {
            addCriterion("res_audicion_lenguaje is null");
            return (Criteria) this;
        }

        public Criteria andRespuestaAudicionLenguajeIsNotNull() {
            addCriterion("res_audicion_lenguaje is not null");
            return (Criteria) this;
        }

        public Criteria andRespuestaAudicionLenguajeEqualTo(String value) {
            addCriterion("res_audicion_lenguaje =", value, "respuestaAudicionLenguaje");
            return (Criteria) this;
        }

        public Criteria andRespuestaAudicionLenguajeNotEqualTo(String value) {
            addCriterion("res_audicion_lenguaje <>", value, "respuestaAudicionLenguaje");
            return (Criteria) this;
        }

        public Criteria andRespuestaAudicionLenguajeGreaterThan(String value) {
            addCriterion("res_audicion_lenguaje >", value, "respuestaAudicionLenguaje");
            return (Criteria) this;
        }

        public Criteria andRespuestaAudicionLenguajeGreaterThanOrEqualTo(String value) {
            addCriterion("res_audicion_lenguaje >=", value, "respuestaAudicionLenguaje");
            return (Criteria) this;
        }

        public Criteria andRespuestaAudicionLenguajeLessThan(String value) {
            addCriterion("res_audicion_lenguaje <", value, "respuestaAudicionLenguaje");
            return (Criteria) this;
        }

        public Criteria andRespuestaAudicionLenguajeLessThanOrEqualTo(String value) {
            addCriterion("res_audicion_lenguaje <=", value, "respuestaAudicionLenguaje");
            return (Criteria) this;
        }

        public Criteria andRespuestaAudicionLenguajeLike(String value) {
            addCriterion("res_audicion_lenguaje like", value, "respuestaAudicionLenguaje");
            return (Criteria) this;
        }

        public Criteria andRespuestaAudicionLenguajeNotLike(String value) {
            addCriterion("res_audicion_lenguaje not like", value, "respuestaAudicionLenguaje");
            return (Criteria) this;
        }

        public Criteria andRespuestaAudicionLenguajeIn(List<String> values) {
            addCriterion("res_audicion_lenguaje in", values, "respuestaAudicionLenguaje");
            return (Criteria) this;
        }

        public Criteria andRespuestaAudicionLenguajeNotIn(List<String> values) {
            addCriterion("res_audicion_lenguaje not in", values, "respuestaAudicionLenguaje");
            return (Criteria) this;
        }

        public Criteria andRespuestaAudicionLenguajeBetween(String value1, String value2) {
            addCriterion("res_audicion_lenguaje between", value1, value2, "respuestaAudicionLenguaje");
            return (Criteria) this;
        }

        public Criteria andRespuestaAudicionLenguajeNotBetween(String value1, String value2) {
            addCriterion("res_audicion_lenguaje not between", value1, value2, "respuestaAudicionLenguaje");
            return (Criteria) this;
        }

        public Criteria andRespuestaPersonalSocialIsNull() {
            addCriterion("res_personal_social is null");
            return (Criteria) this;
        }

        public Criteria andRespuestaPersonalSocialIsNotNull() {
            addCriterion("res_personal_social is not null");
            return (Criteria) this;
        }

        public Criteria andRespuestaPersonalSocialEqualTo(String value) {
            addCriterion("res_personal_social =", value, "respuestaPersonalSocial");
            return (Criteria) this;
        }

        public Criteria andRespuestaPersonalSocialNotEqualTo(String value) {
            addCriterion("res_personal_social <>", value, "respuestaPersonalSocial");
            return (Criteria) this;
        }

        public Criteria andRespuestaPersonalSocialGreaterThan(String value) {
            addCriterion("res_personal_social >", value, "respuestaPersonalSocial");
            return (Criteria) this;
        }

        public Criteria andRespuestaPersonalSocialGreaterThanOrEqualTo(String value) {
            addCriterion("res_personal_social >=", value, "respuestaPersonalSocial");
            return (Criteria) this;
        }

        public Criteria andRespuestaPersonalSocialLessThan(String value) {
            addCriterion("res_personal_social <", value, "respuestaPersonalSocial");
            return (Criteria) this;
        }

        public Criteria andRespuestaPersonalSocialLessThanOrEqualTo(String value) {
            addCriterion("res_personal_social <=", value, "respuestaPersonalSocial");
            return (Criteria) this;
        }

        public Criteria andRespuestaPersonalSocialLike(String value) {
            addCriterion("res_personal_social like", value, "respuestaPersonalSocial");
            return (Criteria) this;
        }

        public Criteria andRespuestaPersonalSocialNotLike(String value) {
            addCriterion("res_personal_social not like", value, "respuestaPersonalSocial");
            return (Criteria) this;
        }

        public Criteria andRespuestaPersonalSocialIn(List<String> values) {
            addCriterion("res_personal_social in", values, "respuestaPersonalSocial");
            return (Criteria) this;
        }

        public Criteria andRespuestaPersonalSocialNotIn(List<String> values) {
            addCriterion("res_personal_social not in", values, "respuestaPersonalSocial");
            return (Criteria) this;
        }

        public Criteria andRespuestaPersonalSocialBetween(String value1, String value2) {
            addCriterion("res_personal_social between", value1, value2, "respuestaPersonalSocial");
            return (Criteria) this;
        }

        public Criteria andRespuestaPersonalSocialNotBetween(String value1, String value2) {
            addCriterion("res_personal_social not between", value1, value2, "respuestaPersonalSocial");
            return (Criteria) this;
        }

        public Criteria andRespuestaTotalIsNull() {
            addCriterion("res_total is null");
            return (Criteria) this;
        }

        public Criteria andRespuestaTotalIsNotNull() {
            addCriterion("res_total is not null");
            return (Criteria) this;
        }

        public Criteria andRespuestaTotalEqualTo(String value) {
            addCriterion("res_total =", value, "respuestaTotal");
            return (Criteria) this;
        }

        public Criteria andRespuestaTotalNotEqualTo(String value) {
            addCriterion("res_total <>", value, "respuestaTotal");
            return (Criteria) this;
        }

        public Criteria andRespuestaTotalGreaterThan(String value) {
            addCriterion("res_total >", value, "respuestaTotal");
            return (Criteria) this;
        }

        public Criteria andRespuestaTotalGreaterThanOrEqualTo(String value) {
            addCriterion("res_total >=", value, "respuestaTotal");
            return (Criteria) this;
        }

        public Criteria andRespuestaTotalLessThan(String value) {
            addCriterion("res_total <", value, "respuestaTotal");
            return (Criteria) this;
        }

        public Criteria andRespuestaTotalLessThanOrEqualTo(String value) {
            addCriterion("res_total <=", value, "respuestaTotal");
            return (Criteria) this;
        }

        public Criteria andRespuestaTotalLike(String value) {
            addCriterion("res_total like", value, "respuestaTotal");
            return (Criteria) this;
        }

        public Criteria andRespuestaTotalNotLike(String value) {
            addCriterion("res_total not like", value, "respuestaTotal");
            return (Criteria) this;
        }

        public Criteria andRespuestaTotalIn(List<String> values) {
            addCriterion("res_total in", values, "respuestaTotal");
            return (Criteria) this;
        }

        public Criteria andRespuestaTotalNotIn(List<String> values) {
            addCriterion("res_total not in", values, "respuestaTotal");
            return (Criteria) this;
        }

        public Criteria andRespuestaTotalBetween(String value1, String value2) {
            addCriterion("res_total between", value1, value2, "respuestaTotal");
            return (Criteria) this;
        }

        public Criteria andRespuestaTotalNotBetween(String value1, String value2) {
            addCriterion("res_total not between", value1, value2, "respuestaTotal");
            return (Criteria) this;
        }

        public Criteria andDiagnosticoIsNull() {
            addCriterion("diagnostico is null");
            return (Criteria) this;
        }

        public Criteria andDiagnosticoIsNotNull() {
            addCriterion("diagnostico is not null");
            return (Criteria) this;
        }

        public Criteria andDiagnosticoEqualTo(String value) {
            addCriterion("diagnostico =", value, "diagnostico");
            return (Criteria) this;
        }

        public Criteria andDiagnosticoNotEqualTo(String value) {
            addCriterion("diagnostico <>", value, "diagnostico");
            return (Criteria) this;
        }

        public Criteria andDiagnosticoGreaterThan(String value) {
            addCriterion("diagnostico >", value, "diagnostico");
            return (Criteria) this;
        }

        public Criteria andDiagnosticoGreaterThanOrEqualTo(String value) {
            addCriterion("diagnostico >=", value, "diagnostico");
            return (Criteria) this;
        }

        public Criteria andDiagnosticoLessThan(String value) {
            addCriterion("diagnostico <", value, "diagnostico");
            return (Criteria) this;
        }

        public Criteria andDiagnosticoLessThanOrEqualTo(String value) {
            addCriterion("diagnostico <=", value, "diagnostico");
            return (Criteria) this;
        }

        public Criteria andDiagnosticoLike(String value) {
            addCriterion("diagnostico like", value, "diagnostico");
            return (Criteria) this;
        }

        public Criteria andDiagnosticoNotLike(String value) {
            addCriterion("diagnostico not like", value, "diagnostico");
            return (Criteria) this;
        }

        public Criteria andDiagnosticoIn(List<String> values) {
            addCriterion("diagnostico in", values, "diagnostico");
            return (Criteria) this;
        }

        public Criteria andDiagnosticoNotIn(List<String> values) {
            addCriterion("diagnostico not in", values, "diagnostico");
            return (Criteria) this;
        }

        public Criteria andDiagnosticoBetween(String value1, String value2) {
            addCriterion("diagnostico between", value1, value2, "diagnostico");
            return (Criteria) this;
        }

        public Criteria andDiagnosticoNotBetween(String value1, String value2) {
            addCriterion("diagnostico not between", value1, value2, "diagnostico");
            return (Criteria) this;
        }

        public Criteria andRecomendacionesIsNull() {
            addCriterion("recomendaciones is null");
            return (Criteria) this;
        }

        public Criteria andRecomendacionesIsNotNull() {
            addCriterion("recomendaciones is not null");
            return (Criteria) this;
        }

        public Criteria andRecomendacionesEqualTo(String value) {
            addCriterion("recomendaciones =", value, "recomendaciones");
            return (Criteria) this;
        }

        public Criteria andRecomendacionesNotEqualTo(String value) {
            addCriterion("recomendaciones <>", value, "recomendaciones");
            return (Criteria) this;
        }

        public Criteria andRecomendacionesGreaterThan(String value) {
            addCriterion("recomendaciones >", value, "recomendaciones");
            return (Criteria) this;
        }

        public Criteria andRecomendacionesGreaterThanOrEqualTo(String value) {
            addCriterion("recomendaciones >=", value, "recomendaciones");
            return (Criteria) this;
        }

        public Criteria andRecomendacionesLessThan(String value) {
            addCriterion("recomendaciones <", value, "recomendaciones");
            return (Criteria) this;
        }

        public Criteria andRecomendacionesLessThanOrEqualTo(String value) {
            addCriterion("recomendaciones <=", value, "recomendaciones");
            return (Criteria) this;
        }

        public Criteria andRecomendacionesLike(String value) {
            addCriterion("recomendaciones like", value, "recomendaciones");
            return (Criteria) this;
        }

        public Criteria andRecomendacionesNotLike(String value) {
            addCriterion("recomendaciones not like", value, "recomendaciones");
            return (Criteria) this;
        }

        public Criteria andRecomendacionesIn(List<String> values) {
            addCriterion("recomendaciones in", values, "recomendaciones");
            return (Criteria) this;
        }

        public Criteria andRecomendacionesNotIn(List<String> values) {
            addCriterion("recomendaciones not in", values, "recomendaciones");
            return (Criteria) this;
        }

        public Criteria andRecomendacionesBetween(String value1, String value2) {
            addCriterion("recomendaciones between", value1, value2, "recomendaciones");
            return (Criteria) this;
        }

        public Criteria andRecomendacionesNotBetween(String value1, String value2) {
            addCriterion("recomendaciones not between", value1, value2, "recomendaciones");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table informe_psicologico
     *
     * @mbggenerated do_not_delete_during_merge Sat Mar 29 13:41:55 BOT 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table informe_psicologico
     *
     * @mbggenerated Sat Mar 29 13:41:55 BOT 2014
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}