package org.quarkbit.trabajosocialsanjuan.dao.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class InformeDetalleExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table informes_detalle
     *
     * @mbggenerated Tue Mar 04 17:35:57 BOT 2014
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table informes_detalle
     *
     * @mbggenerated Tue Mar 04 17:35:57 BOT 2014
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table informes_detalle
     *
     * @mbggenerated Tue Mar 04 17:35:57 BOT 2014
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table informes_detalle
     *
     * @mbggenerated Tue Mar 04 17:35:57 BOT 2014
     */
    public InformeDetalleExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table informes_detalle
     *
     * @mbggenerated Tue Mar 04 17:35:57 BOT 2014
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table informes_detalle
     *
     * @mbggenerated Tue Mar 04 17:35:57 BOT 2014
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table informes_detalle
     *
     * @mbggenerated Tue Mar 04 17:35:57 BOT 2014
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table informes_detalle
     *
     * @mbggenerated Tue Mar 04 17:35:57 BOT 2014
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table informes_detalle
     *
     * @mbggenerated Tue Mar 04 17:35:57 BOT 2014
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table informes_detalle
     *
     * @mbggenerated Tue Mar 04 17:35:57 BOT 2014
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table informes_detalle
     *
     * @mbggenerated Tue Mar 04 17:35:57 BOT 2014
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table informes_detalle
     *
     * @mbggenerated Tue Mar 04 17:35:57 BOT 2014
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table informes_detalle
     *
     * @mbggenerated Tue Mar 04 17:35:57 BOT 2014
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table informes_detalle
     *
     * @mbggenerated Tue Mar 04 17:35:57 BOT 2014
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table informes_detalle
     *
     * @mbggenerated Tue Mar 04 17:35:57 BOT 2014
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andCodigoInformeIsNull() {
            addCriterion("codigo_informe is null");
            return (Criteria) this;
        }

        public Criteria andCodigoInformeIsNotNull() {
            addCriterion("codigo_informe is not null");
            return (Criteria) this;
        }

        public Criteria andCodigoInformeEqualTo(Integer value) {
            addCriterion("codigo_informe =", value, "codigoInforme");
            return (Criteria) this;
        }

        public Criteria andCodigoInformeNotEqualTo(Integer value) {
            addCriterion("codigo_informe <>", value, "codigoInforme");
            return (Criteria) this;
        }

        public Criteria andCodigoInformeGreaterThan(Integer value) {
            addCriterion("codigo_informe >", value, "codigoInforme");
            return (Criteria) this;
        }

        public Criteria andCodigoInformeGreaterThanOrEqualTo(Integer value) {
            addCriterion("codigo_informe >=", value, "codigoInforme");
            return (Criteria) this;
        }

        public Criteria andCodigoInformeLessThan(Integer value) {
            addCriterion("codigo_informe <", value, "codigoInforme");
            return (Criteria) this;
        }

        public Criteria andCodigoInformeLessThanOrEqualTo(Integer value) {
            addCriterion("codigo_informe <=", value, "codigoInforme");
            return (Criteria) this;
        }

        public Criteria andCodigoInformeIn(List<Integer> values) {
            addCriterion("codigo_informe in", values, "codigoInforme");
            return (Criteria) this;
        }

        public Criteria andCodigoInformeNotIn(List<Integer> values) {
            addCriterion("codigo_informe not in", values, "codigoInforme");
            return (Criteria) this;
        }

        public Criteria andCodigoInformeBetween(Integer value1, Integer value2) {
            addCriterion("codigo_informe between", value1, value2, "codigoInforme");
            return (Criteria) this;
        }

        public Criteria andCodigoInformeNotBetween(Integer value1, Integer value2) {
            addCriterion("codigo_informe not between", value1, value2, "codigoInforme");
            return (Criteria) this;
        }

        public Criteria andReferenciaCasoIsNull() {
            addCriterion("referencia_caso is null");
            return (Criteria) this;
        }

        public Criteria andReferenciaCasoIsNotNull() {
            addCriterion("referencia_caso is not null");
            return (Criteria) this;
        }

        public Criteria andReferenciaCasoEqualTo(String value) {
            addCriterion("referencia_caso =", value, "referenciaCaso");
            return (Criteria) this;
        }

        public Criteria andReferenciaCasoNotEqualTo(String value) {
            addCriterion("referencia_caso <>", value, "referenciaCaso");
            return (Criteria) this;
        }

        public Criteria andReferenciaCasoGreaterThan(String value) {
            addCriterion("referencia_caso >", value, "referenciaCaso");
            return (Criteria) this;
        }

        public Criteria andReferenciaCasoGreaterThanOrEqualTo(String value) {
            addCriterion("referencia_caso >=", value, "referenciaCaso");
            return (Criteria) this;
        }

        public Criteria andReferenciaCasoLessThan(String value) {
            addCriterion("referencia_caso <", value, "referenciaCaso");
            return (Criteria) this;
        }

        public Criteria andReferenciaCasoLessThanOrEqualTo(String value) {
            addCriterion("referencia_caso <=", value, "referenciaCaso");
            return (Criteria) this;
        }

        public Criteria andReferenciaCasoLike(String value) {
            addCriterion("referencia_caso like", value, "referenciaCaso");
            return (Criteria) this;
        }

        public Criteria andReferenciaCasoNotLike(String value) {
            addCriterion("referencia_caso not like", value, "referenciaCaso");
            return (Criteria) this;
        }

        public Criteria andReferenciaCasoIn(List<String> values) {
            addCriterion("referencia_caso in", values, "referenciaCaso");
            return (Criteria) this;
        }

        public Criteria andReferenciaCasoNotIn(List<String> values) {
            addCriterion("referencia_caso not in", values, "referenciaCaso");
            return (Criteria) this;
        }

        public Criteria andReferenciaCasoBetween(String value1, String value2) {
            addCriterion("referencia_caso between", value1, value2, "referenciaCaso");
            return (Criteria) this;
        }

        public Criteria andReferenciaCasoNotBetween(String value1, String value2) {
            addCriterion("referencia_caso not between", value1, value2, "referenciaCaso");
            return (Criteria) this;
        }

        public Criteria andFechaInicioIsNull() {
            addCriterion("fecha_inicio is null");
            return (Criteria) this;
        }

        public Criteria andFechaInicioIsNotNull() {
            addCriterion("fecha_inicio is not null");
            return (Criteria) this;
        }

        public Criteria andFechaInicioEqualTo(Date value) {
            addCriterionForJDBCDate("fecha_inicio =", value, "fechaInicio");
            return (Criteria) this;
        }

        public Criteria andFechaInicioNotEqualTo(Date value) {
            addCriterionForJDBCDate("fecha_inicio <>", value, "fechaInicio");
            return (Criteria) this;
        }

        public Criteria andFechaInicioGreaterThan(Date value) {
            addCriterionForJDBCDate("fecha_inicio >", value, "fechaInicio");
            return (Criteria) this;
        }

        public Criteria andFechaInicioGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("fecha_inicio >=", value, "fechaInicio");
            return (Criteria) this;
        }

        public Criteria andFechaInicioLessThan(Date value) {
            addCriterionForJDBCDate("fecha_inicio <", value, "fechaInicio");
            return (Criteria) this;
        }

        public Criteria andFechaInicioLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("fecha_inicio <=", value, "fechaInicio");
            return (Criteria) this;
        }

        public Criteria andFechaInicioIn(List<Date> values) {
            addCriterionForJDBCDate("fecha_inicio in", values, "fechaInicio");
            return (Criteria) this;
        }

        public Criteria andFechaInicioNotIn(List<Date> values) {
            addCriterionForJDBCDate("fecha_inicio not in", values, "fechaInicio");
            return (Criteria) this;
        }

        public Criteria andFechaInicioBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("fecha_inicio between", value1, value2, "fechaInicio");
            return (Criteria) this;
        }

        public Criteria andFechaInicioNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("fecha_inicio not between", value1, value2, "fechaInicio");
            return (Criteria) this;
        }

        public Criteria andFechaFinIsNull() {
            addCriterion("fecha_fin is null");
            return (Criteria) this;
        }

        public Criteria andFechaFinIsNotNull() {
            addCriterion("fecha_fin is not null");
            return (Criteria) this;
        }

        public Criteria andFechaFinEqualTo(Date value) {
            addCriterionForJDBCDate("fecha_fin =", value, "fechaFin");
            return (Criteria) this;
        }

        public Criteria andFechaFinNotEqualTo(Date value) {
            addCriterionForJDBCDate("fecha_fin <>", value, "fechaFin");
            return (Criteria) this;
        }

        public Criteria andFechaFinGreaterThan(Date value) {
            addCriterionForJDBCDate("fecha_fin >", value, "fechaFin");
            return (Criteria) this;
        }

        public Criteria andFechaFinGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("fecha_fin >=", value, "fechaFin");
            return (Criteria) this;
        }

        public Criteria andFechaFinLessThan(Date value) {
            addCriterionForJDBCDate("fecha_fin <", value, "fechaFin");
            return (Criteria) this;
        }

        public Criteria andFechaFinLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("fecha_fin <=", value, "fechaFin");
            return (Criteria) this;
        }

        public Criteria andFechaFinIn(List<Date> values) {
            addCriterionForJDBCDate("fecha_fin in", values, "fechaFin");
            return (Criteria) this;
        }

        public Criteria andFechaFinNotIn(List<Date> values) {
            addCriterionForJDBCDate("fecha_fin not in", values, "fechaFin");
            return (Criteria) this;
        }

        public Criteria andFechaFinBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("fecha_fin between", value1, value2, "fechaFin");
            return (Criteria) this;
        }

        public Criteria andFechaFinNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("fecha_fin not between", value1, value2, "fechaFin");
            return (Criteria) this;
        }

        public Criteria andSituacionHabitacionalIsNull() {
            addCriterion("situacion_habitacional is null");
            return (Criteria) this;
        }

        public Criteria andSituacionHabitacionalIsNotNull() {
            addCriterion("situacion_habitacional is not null");
            return (Criteria) this;
        }

        public Criteria andSituacionHabitacionalEqualTo(String value) {
            addCriterion("situacion_habitacional =", value, "situacionHabitacional");
            return (Criteria) this;
        }

        public Criteria andSituacionHabitacionalNotEqualTo(String value) {
            addCriterion("situacion_habitacional <>", value, "situacionHabitacional");
            return (Criteria) this;
        }

        public Criteria andSituacionHabitacionalGreaterThan(String value) {
            addCriterion("situacion_habitacional >", value, "situacionHabitacional");
            return (Criteria) this;
        }

        public Criteria andSituacionHabitacionalGreaterThanOrEqualTo(String value) {
            addCriterion("situacion_habitacional >=", value, "situacionHabitacional");
            return (Criteria) this;
        }

        public Criteria andSituacionHabitacionalLessThan(String value) {
            addCriterion("situacion_habitacional <", value, "situacionHabitacional");
            return (Criteria) this;
        }

        public Criteria andSituacionHabitacionalLessThanOrEqualTo(String value) {
            addCriterion("situacion_habitacional <=", value, "situacionHabitacional");
            return (Criteria) this;
        }

        public Criteria andSituacionHabitacionalLike(String value) {
            addCriterion("situacion_habitacional like", value, "situacionHabitacional");
            return (Criteria) this;
        }

        public Criteria andSituacionHabitacionalNotLike(String value) {
            addCriterion("situacion_habitacional not like", value, "situacionHabitacional");
            return (Criteria) this;
        }

        public Criteria andSituacionHabitacionalIn(List<String> values) {
            addCriterion("situacion_habitacional in", values, "situacionHabitacional");
            return (Criteria) this;
        }

        public Criteria andSituacionHabitacionalNotIn(List<String> values) {
            addCriterion("situacion_habitacional not in", values, "situacionHabitacional");
            return (Criteria) this;
        }

        public Criteria andSituacionHabitacionalBetween(String value1, String value2) {
            addCriterion("situacion_habitacional between", value1, value2, "situacionHabitacional");
            return (Criteria) this;
        }

        public Criteria andSituacionHabitacionalNotBetween(String value1, String value2) {
            addCriterion("situacion_habitacional not between", value1, value2, "situacionHabitacional");
            return (Criteria) this;
        }

        public Criteria andIntegracionFamiliarIsNull() {
            addCriterion("integracion_familiar is null");
            return (Criteria) this;
        }

        public Criteria andIntegracionFamiliarIsNotNull() {
            addCriterion("integracion_familiar is not null");
            return (Criteria) this;
        }

        public Criteria andIntegracionFamiliarEqualTo(String value) {
            addCriterion("integracion_familiar =", value, "integracionFamiliar");
            return (Criteria) this;
        }

        public Criteria andIntegracionFamiliarNotEqualTo(String value) {
            addCriterion("integracion_familiar <>", value, "integracionFamiliar");
            return (Criteria) this;
        }

        public Criteria andIntegracionFamiliarGreaterThan(String value) {
            addCriterion("integracion_familiar >", value, "integracionFamiliar");
            return (Criteria) this;
        }

        public Criteria andIntegracionFamiliarGreaterThanOrEqualTo(String value) {
            addCriterion("integracion_familiar >=", value, "integracionFamiliar");
            return (Criteria) this;
        }

        public Criteria andIntegracionFamiliarLessThan(String value) {
            addCriterion("integracion_familiar <", value, "integracionFamiliar");
            return (Criteria) this;
        }

        public Criteria andIntegracionFamiliarLessThanOrEqualTo(String value) {
            addCriterion("integracion_familiar <=", value, "integracionFamiliar");
            return (Criteria) this;
        }

        public Criteria andIntegracionFamiliarLike(String value) {
            addCriterion("integracion_familiar like", value, "integracionFamiliar");
            return (Criteria) this;
        }

        public Criteria andIntegracionFamiliarNotLike(String value) {
            addCriterion("integracion_familiar not like", value, "integracionFamiliar");
            return (Criteria) this;
        }

        public Criteria andIntegracionFamiliarIn(List<String> values) {
            addCriterion("integracion_familiar in", values, "integracionFamiliar");
            return (Criteria) this;
        }

        public Criteria andIntegracionFamiliarNotIn(List<String> values) {
            addCriterion("integracion_familiar not in", values, "integracionFamiliar");
            return (Criteria) this;
        }

        public Criteria andIntegracionFamiliarBetween(String value1, String value2) {
            addCriterion("integracion_familiar between", value1, value2, "integracionFamiliar");
            return (Criteria) this;
        }

        public Criteria andIntegracionFamiliarNotBetween(String value1, String value2) {
            addCriterion("integracion_familiar not between", value1, value2, "integracionFamiliar");
            return (Criteria) this;
        }

        public Criteria andDesarrolloAfectivoIsNull() {
            addCriterion("desarrollo_afectivo is null");
            return (Criteria) this;
        }

        public Criteria andDesarrolloAfectivoIsNotNull() {
            addCriterion("desarrollo_afectivo is not null");
            return (Criteria) this;
        }

        public Criteria andDesarrolloAfectivoEqualTo(String value) {
            addCriterion("desarrollo_afectivo =", value, "desarrolloAfectivo");
            return (Criteria) this;
        }

        public Criteria andDesarrolloAfectivoNotEqualTo(String value) {
            addCriterion("desarrollo_afectivo <>", value, "desarrolloAfectivo");
            return (Criteria) this;
        }

        public Criteria andDesarrolloAfectivoGreaterThan(String value) {
            addCriterion("desarrollo_afectivo >", value, "desarrolloAfectivo");
            return (Criteria) this;
        }

        public Criteria andDesarrolloAfectivoGreaterThanOrEqualTo(String value) {
            addCriterion("desarrollo_afectivo >=", value, "desarrolloAfectivo");
            return (Criteria) this;
        }

        public Criteria andDesarrolloAfectivoLessThan(String value) {
            addCriterion("desarrollo_afectivo <", value, "desarrolloAfectivo");
            return (Criteria) this;
        }

        public Criteria andDesarrolloAfectivoLessThanOrEqualTo(String value) {
            addCriterion("desarrollo_afectivo <=", value, "desarrolloAfectivo");
            return (Criteria) this;
        }

        public Criteria andDesarrolloAfectivoLike(String value) {
            addCriterion("desarrollo_afectivo like", value, "desarrolloAfectivo");
            return (Criteria) this;
        }

        public Criteria andDesarrolloAfectivoNotLike(String value) {
            addCriterion("desarrollo_afectivo not like", value, "desarrolloAfectivo");
            return (Criteria) this;
        }

        public Criteria andDesarrolloAfectivoIn(List<String> values) {
            addCriterion("desarrollo_afectivo in", values, "desarrolloAfectivo");
            return (Criteria) this;
        }

        public Criteria andDesarrolloAfectivoNotIn(List<String> values) {
            addCriterion("desarrollo_afectivo not in", values, "desarrolloAfectivo");
            return (Criteria) this;
        }

        public Criteria andDesarrolloAfectivoBetween(String value1, String value2) {
            addCriterion("desarrollo_afectivo between", value1, value2, "desarrolloAfectivo");
            return (Criteria) this;
        }

        public Criteria andDesarrolloAfectivoNotBetween(String value1, String value2) {
            addCriterion("desarrollo_afectivo not between", value1, value2, "desarrolloAfectivo");
            return (Criteria) this;
        }

        public Criteria andHistoriaSocialIsNull() {
            addCriterion("historia_social is null");
            return (Criteria) this;
        }

        public Criteria andHistoriaSocialIsNotNull() {
            addCriterion("historia_social is not null");
            return (Criteria) this;
        }

        public Criteria andHistoriaSocialEqualTo(String value) {
            addCriterion("historia_social =", value, "historiaSocial");
            return (Criteria) this;
        }

        public Criteria andHistoriaSocialNotEqualTo(String value) {
            addCriterion("historia_social <>", value, "historiaSocial");
            return (Criteria) this;
        }

        public Criteria andHistoriaSocialGreaterThan(String value) {
            addCriterion("historia_social >", value, "historiaSocial");
            return (Criteria) this;
        }

        public Criteria andHistoriaSocialGreaterThanOrEqualTo(String value) {
            addCriterion("historia_social >=", value, "historiaSocial");
            return (Criteria) this;
        }

        public Criteria andHistoriaSocialLessThan(String value) {
            addCriterion("historia_social <", value, "historiaSocial");
            return (Criteria) this;
        }

        public Criteria andHistoriaSocialLessThanOrEqualTo(String value) {
            addCriterion("historia_social <=", value, "historiaSocial");
            return (Criteria) this;
        }

        public Criteria andHistoriaSocialLike(String value) {
            addCriterion("historia_social like", value, "historiaSocial");
            return (Criteria) this;
        }

        public Criteria andHistoriaSocialNotLike(String value) {
            addCriterion("historia_social not like", value, "historiaSocial");
            return (Criteria) this;
        }

        public Criteria andHistoriaSocialIn(List<String> values) {
            addCriterion("historia_social in", values, "historiaSocial");
            return (Criteria) this;
        }

        public Criteria andHistoriaSocialNotIn(List<String> values) {
            addCriterion("historia_social not in", values, "historiaSocial");
            return (Criteria) this;
        }

        public Criteria andHistoriaSocialBetween(String value1, String value2) {
            addCriterion("historia_social between", value1, value2, "historiaSocial");
            return (Criteria) this;
        }

        public Criteria andHistoriaSocialNotBetween(String value1, String value2) {
            addCriterion("historia_social not between", value1, value2, "historiaSocial");
            return (Criteria) this;
        }

        public Criteria andSituacionActualIsNull() {
            addCriterion("situacion_actual is null");
            return (Criteria) this;
        }

        public Criteria andSituacionActualIsNotNull() {
            addCriterion("situacion_actual is not null");
            return (Criteria) this;
        }

        public Criteria andSituacionActualEqualTo(String value) {
            addCriterion("situacion_actual =", value, "situacionActual");
            return (Criteria) this;
        }

        public Criteria andSituacionActualNotEqualTo(String value) {
            addCriterion("situacion_actual <>", value, "situacionActual");
            return (Criteria) this;
        }

        public Criteria andSituacionActualGreaterThan(String value) {
            addCriterion("situacion_actual >", value, "situacionActual");
            return (Criteria) this;
        }

        public Criteria andSituacionActualGreaterThanOrEqualTo(String value) {
            addCriterion("situacion_actual >=", value, "situacionActual");
            return (Criteria) this;
        }

        public Criteria andSituacionActualLessThan(String value) {
            addCriterion("situacion_actual <", value, "situacionActual");
            return (Criteria) this;
        }

        public Criteria andSituacionActualLessThanOrEqualTo(String value) {
            addCriterion("situacion_actual <=", value, "situacionActual");
            return (Criteria) this;
        }

        public Criteria andSituacionActualLike(String value) {
            addCriterion("situacion_actual like", value, "situacionActual");
            return (Criteria) this;
        }

        public Criteria andSituacionActualNotLike(String value) {
            addCriterion("situacion_actual not like", value, "situacionActual");
            return (Criteria) this;
        }

        public Criteria andSituacionActualIn(List<String> values) {
            addCriterion("situacion_actual in", values, "situacionActual");
            return (Criteria) this;
        }

        public Criteria andSituacionActualNotIn(List<String> values) {
            addCriterion("situacion_actual not in", values, "situacionActual");
            return (Criteria) this;
        }

        public Criteria andSituacionActualBetween(String value1, String value2) {
            addCriterion("situacion_actual between", value1, value2, "situacionActual");
            return (Criteria) this;
        }

        public Criteria andSituacionActualNotBetween(String value1, String value2) {
            addCriterion("situacion_actual not between", value1, value2, "situacionActual");
            return (Criteria) this;
        }

        public Criteria andFuentesInformacionIsNull() {
            addCriterion("fuentes_informacion is null");
            return (Criteria) this;
        }

        public Criteria andFuentesInformacionIsNotNull() {
            addCriterion("fuentes_informacion is not null");
            return (Criteria) this;
        }

        public Criteria andFuentesInformacionEqualTo(String value) {
            addCriterion("fuentes_informacion =", value, "fuentesInformacion");
            return (Criteria) this;
        }

        public Criteria andFuentesInformacionNotEqualTo(String value) {
            addCriterion("fuentes_informacion <>", value, "fuentesInformacion");
            return (Criteria) this;
        }

        public Criteria andFuentesInformacionGreaterThan(String value) {
            addCriterion("fuentes_informacion >", value, "fuentesInformacion");
            return (Criteria) this;
        }

        public Criteria andFuentesInformacionGreaterThanOrEqualTo(String value) {
            addCriterion("fuentes_informacion >=", value, "fuentesInformacion");
            return (Criteria) this;
        }

        public Criteria andFuentesInformacionLessThan(String value) {
            addCriterion("fuentes_informacion <", value, "fuentesInformacion");
            return (Criteria) this;
        }

        public Criteria andFuentesInformacionLessThanOrEqualTo(String value) {
            addCriterion("fuentes_informacion <=", value, "fuentesInformacion");
            return (Criteria) this;
        }

        public Criteria andFuentesInformacionLike(String value) {
            addCriterion("fuentes_informacion like", value, "fuentesInformacion");
            return (Criteria) this;
        }

        public Criteria andFuentesInformacionNotLike(String value) {
            addCriterion("fuentes_informacion not like", value, "fuentesInformacion");
            return (Criteria) this;
        }

        public Criteria andFuentesInformacionIn(List<String> values) {
            addCriterion("fuentes_informacion in", values, "fuentesInformacion");
            return (Criteria) this;
        }

        public Criteria andFuentesInformacionNotIn(List<String> values) {
            addCriterion("fuentes_informacion not in", values, "fuentesInformacion");
            return (Criteria) this;
        }

        public Criteria andFuentesInformacionBetween(String value1, String value2) {
            addCriterion("fuentes_informacion between", value1, value2, "fuentesInformacion");
            return (Criteria) this;
        }

        public Criteria andFuentesInformacionNotBetween(String value1, String value2) {
            addCriterion("fuentes_informacion not between", value1, value2, "fuentesInformacion");
            return (Criteria) this;
        }

        public Criteria andDescripcionCasoIsNull() {
            addCriterion("descripcion_caso is null");
            return (Criteria) this;
        }

        public Criteria andDescripcionCasoIsNotNull() {
            addCriterion("descripcion_caso is not null");
            return (Criteria) this;
        }

        public Criteria andDescripcionCasoEqualTo(String value) {
            addCriterion("descripcion_caso =", value, "descripcionCaso");
            return (Criteria) this;
        }

        public Criteria andDescripcionCasoNotEqualTo(String value) {
            addCriterion("descripcion_caso <>", value, "descripcionCaso");
            return (Criteria) this;
        }

        public Criteria andDescripcionCasoGreaterThan(String value) {
            addCriterion("descripcion_caso >", value, "descripcionCaso");
            return (Criteria) this;
        }

        public Criteria andDescripcionCasoGreaterThanOrEqualTo(String value) {
            addCriterion("descripcion_caso >=", value, "descripcionCaso");
            return (Criteria) this;
        }

        public Criteria andDescripcionCasoLessThan(String value) {
            addCriterion("descripcion_caso <", value, "descripcionCaso");
            return (Criteria) this;
        }

        public Criteria andDescripcionCasoLessThanOrEqualTo(String value) {
            addCriterion("descripcion_caso <=", value, "descripcionCaso");
            return (Criteria) this;
        }

        public Criteria andDescripcionCasoLike(String value) {
            addCriterion("descripcion_caso like", value, "descripcionCaso");
            return (Criteria) this;
        }

        public Criteria andDescripcionCasoNotLike(String value) {
            addCriterion("descripcion_caso not like", value, "descripcionCaso");
            return (Criteria) this;
        }

        public Criteria andDescripcionCasoIn(List<String> values) {
            addCriterion("descripcion_caso in", values, "descripcionCaso");
            return (Criteria) this;
        }

        public Criteria andDescripcionCasoNotIn(List<String> values) {
            addCriterion("descripcion_caso not in", values, "descripcionCaso");
            return (Criteria) this;
        }

        public Criteria andDescripcionCasoBetween(String value1, String value2) {
            addCriterion("descripcion_caso between", value1, value2, "descripcionCaso");
            return (Criteria) this;
        }

        public Criteria andDescripcionCasoNotBetween(String value1, String value2) {
            addCriterion("descripcion_caso not between", value1, value2, "descripcionCaso");
            return (Criteria) this;
        }

        public Criteria andDocumentosAdjuntosIsNull() {
            addCriterion("documentos_adjuntos is null");
            return (Criteria) this;
        }

        public Criteria andDocumentosAdjuntosIsNotNull() {
            addCriterion("documentos_adjuntos is not null");
            return (Criteria) this;
        }

        public Criteria andDocumentosAdjuntosEqualTo(String value) {
            addCriterion("documentos_adjuntos =", value, "documentosAdjuntos");
            return (Criteria) this;
        }

        public Criteria andDocumentosAdjuntosNotEqualTo(String value) {
            addCriterion("documentos_adjuntos <>", value, "documentosAdjuntos");
            return (Criteria) this;
        }

        public Criteria andDocumentosAdjuntosGreaterThan(String value) {
            addCriterion("documentos_adjuntos >", value, "documentosAdjuntos");
            return (Criteria) this;
        }

        public Criteria andDocumentosAdjuntosGreaterThanOrEqualTo(String value) {
            addCriterion("documentos_adjuntos >=", value, "documentosAdjuntos");
            return (Criteria) this;
        }

        public Criteria andDocumentosAdjuntosLessThan(String value) {
            addCriterion("documentos_adjuntos <", value, "documentosAdjuntos");
            return (Criteria) this;
        }

        public Criteria andDocumentosAdjuntosLessThanOrEqualTo(String value) {
            addCriterion("documentos_adjuntos <=", value, "documentosAdjuntos");
            return (Criteria) this;
        }

        public Criteria andDocumentosAdjuntosLike(String value) {
            addCriterion("documentos_adjuntos like", value, "documentosAdjuntos");
            return (Criteria) this;
        }

        public Criteria andDocumentosAdjuntosNotLike(String value) {
            addCriterion("documentos_adjuntos not like", value, "documentosAdjuntos");
            return (Criteria) this;
        }

        public Criteria andDocumentosAdjuntosIn(List<String> values) {
            addCriterion("documentos_adjuntos in", values, "documentosAdjuntos");
            return (Criteria) this;
        }

        public Criteria andDocumentosAdjuntosNotIn(List<String> values) {
            addCriterion("documentos_adjuntos not in", values, "documentosAdjuntos");
            return (Criteria) this;
        }

        public Criteria andDocumentosAdjuntosBetween(String value1, String value2) {
            addCriterion("documentos_adjuntos between", value1, value2, "documentosAdjuntos");
            return (Criteria) this;
        }

        public Criteria andDocumentosAdjuntosNotBetween(String value1, String value2) {
            addCriterion("documentos_adjuntos not between", value1, value2, "documentosAdjuntos");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table informes_detalle
     *
     * @mbggenerated do_not_delete_during_merge Tue Mar 04 17:35:57 BOT 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table informes_detalle
     *
     * @mbggenerated Tue Mar 04 17:35:57 BOT 2014
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}