package org.quarkbit.trabajosocialsanjuan.dao.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class InformeExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table informes
     *
     * @mbggenerated Tue Mar 04 17:35:56 BOT 2014
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table informes
     *
     * @mbggenerated Tue Mar 04 17:35:56 BOT 2014
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table informes
     *
     * @mbggenerated Tue Mar 04 17:35:56 BOT 2014
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table informes
     *
     * @mbggenerated Tue Mar 04 17:35:56 BOT 2014
     */
    public InformeExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table informes
     *
     * @mbggenerated Tue Mar 04 17:35:56 BOT 2014
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table informes
     *
     * @mbggenerated Tue Mar 04 17:35:56 BOT 2014
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table informes
     *
     * @mbggenerated Tue Mar 04 17:35:56 BOT 2014
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table informes
     *
     * @mbggenerated Tue Mar 04 17:35:56 BOT 2014
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table informes
     *
     * @mbggenerated Tue Mar 04 17:35:56 BOT 2014
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table informes
     *
     * @mbggenerated Tue Mar 04 17:35:56 BOT 2014
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table informes
     *
     * @mbggenerated Tue Mar 04 17:35:56 BOT 2014
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table informes
     *
     * @mbggenerated Tue Mar 04 17:35:56 BOT 2014
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table informes
     *
     * @mbggenerated Tue Mar 04 17:35:56 BOT 2014
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table informes
     *
     * @mbggenerated Tue Mar 04 17:35:56 BOT 2014
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table informes
     *
     * @mbggenerated Tue Mar 04 17:35:56 BOT 2014
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andCodigoInformeIsNull() {
            addCriterion("i.codigo_informe is null");
            return (Criteria) this;
        }

        public Criteria andCodigoInformeIsNotNull() {
            addCriterion("i.codigo_informe is not null");
            return (Criteria) this;
        }

        public Criteria andCodigoInformeEqualTo(Integer value) {
            addCriterion("i.codigo_informe =", value, "codigoInforme");
            return (Criteria) this;
        }

        public Criteria andCodigoInformeNotEqualTo(Integer value) {
            addCriterion("i.codigo_informe <>", value, "codigoInforme");
            return (Criteria) this;
        }

        public Criteria andCodigoInformeGreaterThan(Integer value) {
            addCriterion("i.codigo_informe >", value, "codigoInforme");
            return (Criteria) this;
        }

        public Criteria andCodigoInformeGreaterThanOrEqualTo(Integer value) {
            addCriterion("i.codigo_informe >=", value, "codigoInforme");
            return (Criteria) this;
        }

        public Criteria andCodigoInformeLessThan(Integer value) {
            addCriterion("i.codigo_informe <", value, "codigoInforme");
            return (Criteria) this;
        }

        public Criteria andCodigoInformeLessThanOrEqualTo(Integer value) {
            addCriterion("i.codigo_informe <=", value, "codigoInforme");
            return (Criteria) this;
        }

        public Criteria andCodigoInformeIn(List<Integer> values) {
            addCriterion("i.codigo_informe in", values, "codigoInforme");
            return (Criteria) this;
        }

        public Criteria andCodigoInformeNotIn(List<Integer> values) {
            addCriterion("i.codigo_informe not in", values, "codigoInforme");
            return (Criteria) this;
        }

        public Criteria andCodigoInformeBetween(Integer value1, Integer value2) {
            addCriterion("i.codigo_informe between", value1, value2, "codigoInforme");
            return (Criteria) this;
        }

        public Criteria andCodigoInformeNotBetween(Integer value1, Integer value2) {
            addCriterion("i.codigo_informe not between", value1, value2, "codigoInforme");
            return (Criteria) this;
        }

        public Criteria andCodigoKardexIsNull() {
            addCriterion("codigo_kardex is null");
            return (Criteria) this;
        }

        public Criteria andCodigoKardexIsNotNull() {
            addCriterion("codigo_kardex is not null");
            return (Criteria) this;
        }

        public Criteria andCodigoKardexEqualTo(Integer value) {
            addCriterion("codigo_kardex =", value, "codigoKardex");
            return (Criteria) this;
        }

        public Criteria andCodigoKardexNotEqualTo(Integer value) {
            addCriterion("codigo_kardex <>", value, "codigoKardex");
            return (Criteria) this;
        }

        public Criteria andCodigoKardexGreaterThan(Integer value) {
            addCriterion("codigo_kardex >", value, "codigoKardex");
            return (Criteria) this;
        }

        public Criteria andCodigoKardexGreaterThanOrEqualTo(Integer value) {
            addCriterion("codigo_kardex >=", value, "codigoKardex");
            return (Criteria) this;
        }

        public Criteria andCodigoKardexLessThan(Integer value) {
            addCriterion("codigo_kardex <", value, "codigoKardex");
            return (Criteria) this;
        }

        public Criteria andCodigoKardexLessThanOrEqualTo(Integer value) {
            addCriterion("codigo_kardex <=", value, "codigoKardex");
            return (Criteria) this;
        }

        public Criteria andCodigoKardexIn(List<Integer> values) {
            addCriterion("codigo_kardex in", values, "codigoKardex");
            return (Criteria) this;
        }

        public Criteria andCodigoKardexNotIn(List<Integer> values) {
            addCriterion("codigo_kardex not in", values, "codigoKardex");
            return (Criteria) this;
        }

        public Criteria andCodigoKardexBetween(Integer value1, Integer value2) {
            addCriterion("codigo_kardex between", value1, value2, "codigoKardex");
            return (Criteria) this;
        }

        public Criteria andCodigoKardexNotBetween(Integer value1, Integer value2) {
            addCriterion("codigo_kardex not between", value1, value2, "codigoKardex");
            return (Criteria) this;
        }

        public Criteria andCodigoInstitucionIsNull() {
            addCriterion("codigo_institucion is null");
            return (Criteria) this;
        }

        public Criteria andCodigoInstitucionIsNotNull() {
            addCriterion("codigo_institucion is not null");
            return (Criteria) this;
        }

        public Criteria andCodigoInstitucionEqualTo(Integer value) {
            addCriterion("codigo_institucion =", value, "codigoInstitucion");
            return (Criteria) this;
        }

        public Criteria andCodigoInstitucionNotEqualTo(Integer value) {
            addCriterion("codigo_institucion <>", value, "codigoInstitucion");
            return (Criteria) this;
        }

        public Criteria andCodigoInstitucionGreaterThan(Integer value) {
            addCriterion("codigo_institucion >", value, "codigoInstitucion");
            return (Criteria) this;
        }

        public Criteria andCodigoInstitucionGreaterThanOrEqualTo(Integer value) {
            addCriterion("codigo_institucion >=", value, "codigoInstitucion");
            return (Criteria) this;
        }

        public Criteria andCodigoInstitucionLessThan(Integer value) {
            addCriterion("codigo_institucion <", value, "codigoInstitucion");
            return (Criteria) this;
        }

        public Criteria andCodigoInstitucionLessThanOrEqualTo(Integer value) {
            addCriterion("codigo_institucion <=", value, "codigoInstitucion");
            return (Criteria) this;
        }

        public Criteria andCodigoInstitucionIn(List<Integer> values) {
            addCriterion("codigo_institucion in", values, "codigoInstitucion");
            return (Criteria) this;
        }

        public Criteria andCodigoInstitucionNotIn(List<Integer> values) {
            addCriterion("codigo_institucion not in", values, "codigoInstitucion");
            return (Criteria) this;
        }

        public Criteria andCodigoInstitucionBetween(Integer value1, Integer value2) {
            addCriterion("codigo_institucion between", value1, value2, "codigoInstitucion");
            return (Criteria) this;
        }

        public Criteria andCodigoInstitucionNotBetween(Integer value1, Integer value2) {
            addCriterion("codigo_institucion not between", value1, value2, "codigoInstitucion");
            return (Criteria) this;
        }

        public Criteria andCodigoTipoInformeIsNull() {
            addCriterion("codigo_tipo_informe is null");
            return (Criteria) this;
        }

        public Criteria andCodigoTipoInformeIsNotNull() {
            addCriterion("codigo_tipo_informe is not null");
            return (Criteria) this;
        }

        public Criteria andCodigoTipoInformeEqualTo(String value) {
            addCriterion("codigo_tipo_informe =", value, "codigoTipoInforme");
            return (Criteria) this;
        }

        public Criteria andCodigoTipoInformeNotEqualTo(String value) {
            addCriterion("codigo_tipo_informe <>", value, "codigoTipoInforme");
            return (Criteria) this;
        }

        public Criteria andCodigoTipoInformeGreaterThan(String value) {
            addCriterion("codigo_tipo_informe >", value, "codigoTipoInforme");
            return (Criteria) this;
        }

        public Criteria andCodigoTipoInformeGreaterThanOrEqualTo(String value) {
            addCriterion("codigo_tipo_informe >=", value, "codigoTipoInforme");
            return (Criteria) this;
        }

        public Criteria andCodigoTipoInformeLessThan(String value) {
            addCriterion("codigo_tipo_informe <", value, "codigoTipoInforme");
            return (Criteria) this;
        }

        public Criteria andCodigoTipoInformeLessThanOrEqualTo(String value) {
            addCriterion("codigo_tipo_informe <=", value, "codigoTipoInforme");
            return (Criteria) this;
        }

        public Criteria andCodigoTipoInformeLike(String value) {
            addCriterion("codigo_tipo_informe like", value, "codigoTipoInforme");
            return (Criteria) this;
        }

        public Criteria andCodigoTipoInformeNotLike(String value) {
            addCriterion("codigo_tipo_informe not like", value, "codigoTipoInforme");
            return (Criteria) this;
        }

        public Criteria andCodigoTipoInformeIn(List<String> values) {
            addCriterion("codigo_tipo_informe in", values, "codigoTipoInforme");
            return (Criteria) this;
        }

        public Criteria andCodigoTipoInformeNotIn(List<String> values) {
            addCriterion("codigo_tipo_informe not in", values, "codigoTipoInforme");
            return (Criteria) this;
        }

        public Criteria andCodigoTipoInformeBetween(String value1, String value2) {
            addCriterion("codigo_tipo_informe between", value1, value2, "codigoTipoInforme");
            return (Criteria) this;
        }

        public Criteria andCodigoTipoInformeNotBetween(String value1, String value2) {
            addCriterion("codigo_tipo_informe not between", value1, value2, "codigoTipoInforme");
            return (Criteria) this;
        }

        public Criteria andCodigoPersonaDirigidoIsNull() {
            addCriterion("codigo_persona_dirigido is null");
            return (Criteria) this;
        }

        public Criteria andCodigoPersonaDirigidoIsNotNull() {
            addCriterion("codigo_persona_dirigido is not null");
            return (Criteria) this;
        }

        public Criteria andCodigoPersonaDirigidoEqualTo(Integer value) {
            addCriterion("codigo_persona_dirigido =", value, "codigoPersonaDirigido");
            return (Criteria) this;
        }

        public Criteria andCodigoPersonaDirigidoNotEqualTo(Integer value) {
            addCriterion("codigo_persona_dirigido <>", value, "codigoPersonaDirigido");
            return (Criteria) this;
        }

        public Criteria andCodigoPersonaDirigidoGreaterThan(Integer value) {
            addCriterion("codigo_persona_dirigido >", value, "codigoPersonaDirigido");
            return (Criteria) this;
        }

        public Criteria andCodigoPersonaDirigidoGreaterThanOrEqualTo(Integer value) {
            addCriterion("codigo_persona_dirigido >=", value, "codigoPersonaDirigido");
            return (Criteria) this;
        }

        public Criteria andCodigoPersonaDirigidoLessThan(Integer value) {
            addCriterion("codigo_persona_dirigido <", value, "codigoPersonaDirigido");
            return (Criteria) this;
        }

        public Criteria andCodigoPersonaDirigidoLessThanOrEqualTo(Integer value) {
            addCriterion("codigo_persona_dirigido <=", value, "codigoPersonaDirigido");
            return (Criteria) this;
        }

        public Criteria andCodigoPersonaDirigidoIn(List<Integer> values) {
            addCriterion("codigo_persona_dirigido in", values, "codigoPersonaDirigido");
            return (Criteria) this;
        }

        public Criteria andCodigoPersonaDirigidoNotIn(List<Integer> values) {
            addCriterion("codigo_persona_dirigido not in", values, "codigoPersonaDirigido");
            return (Criteria) this;
        }

        public Criteria andCodigoPersonaDirigidoBetween(Integer value1, Integer value2) {
            addCriterion("codigo_persona_dirigido between", value1, value2, "codigoPersonaDirigido");
            return (Criteria) this;
        }

        public Criteria andCodigoPersonaDirigidoNotBetween(Integer value1, Integer value2) {
            addCriterion("codigo_persona_dirigido not between", value1, value2, "codigoPersonaDirigido");
            return (Criteria) this;
        }

        public Criteria andCodigoPersonaViaIsNull() {
            addCriterion("codigo_persona_via is null");
            return (Criteria) this;
        }

        public Criteria andCodigoPersonaViaIsNotNull() {
            addCriterion("codigo_persona_via is not null");
            return (Criteria) this;
        }

        public Criteria andCodigoPersonaViaEqualTo(Integer value) {
            addCriterion("codigo_persona_via =", value, "codigoPersonaVia");
            return (Criteria) this;
        }

        public Criteria andCodigoPersonaViaNotEqualTo(Integer value) {
            addCriterion("codigo_persona_via <>", value, "codigoPersonaVia");
            return (Criteria) this;
        }

        public Criteria andCodigoPersonaViaGreaterThan(Integer value) {
            addCriterion("codigo_persona_via >", value, "codigoPersonaVia");
            return (Criteria) this;
        }

        public Criteria andCodigoPersonaViaGreaterThanOrEqualTo(Integer value) {
            addCriterion("codigo_persona_via >=", value, "codigoPersonaVia");
            return (Criteria) this;
        }

        public Criteria andCodigoPersonaViaLessThan(Integer value) {
            addCriterion("codigo_persona_via <", value, "codigoPersonaVia");
            return (Criteria) this;
        }

        public Criteria andCodigoPersonaViaLessThanOrEqualTo(Integer value) {
            addCriterion("codigo_persona_via <=", value, "codigoPersonaVia");
            return (Criteria) this;
        }

        public Criteria andCodigoPersonaViaIn(List<Integer> values) {
            addCriterion("codigo_persona_via in", values, "codigoPersonaVia");
            return (Criteria) this;
        }

        public Criteria andCodigoPersonaViaNotIn(List<Integer> values) {
            addCriterion("codigo_persona_via not in", values, "codigoPersonaVia");
            return (Criteria) this;
        }

        public Criteria andCodigoPersonaViaBetween(Integer value1, Integer value2) {
            addCriterion("codigo_persona_via between", value1, value2, "codigoPersonaVia");
            return (Criteria) this;
        }

        public Criteria andCodigoPersonaViaNotBetween(Integer value1, Integer value2) {
            addCriterion("codigo_persona_via not between", value1, value2, "codigoPersonaVia");
            return (Criteria) this;
        }

        public Criteria andCodigoPersonaDe1IsNull() {
            addCriterion("codigo_persona_de_01 is null");
            return (Criteria) this;
        }

        public Criteria andCodigoPersonaDe1IsNotNull() {
            addCriterion("codigo_persona_de_01 is not null");
            return (Criteria) this;
        }

        public Criteria andCodigoPersonaDe1EqualTo(Integer value) {
            addCriterion("codigo_persona_de_01 =", value, "codigoPersonaDe1");
            return (Criteria) this;
        }

        public Criteria andCodigoPersonaDe1NotEqualTo(Integer value) {
            addCriterion("codigo_persona_de_01 <>", value, "codigoPersonaDe1");
            return (Criteria) this;
        }

        public Criteria andCodigoPersonaDe1GreaterThan(Integer value) {
            addCriterion("codigo_persona_de_01 >", value, "codigoPersonaDe1");
            return (Criteria) this;
        }

        public Criteria andCodigoPersonaDe1GreaterThanOrEqualTo(Integer value) {
            addCriterion("codigo_persona_de_01 >=", value, "codigoPersonaDe1");
            return (Criteria) this;
        }

        public Criteria andCodigoPersonaDe1LessThan(Integer value) {
            addCriterion("codigo_persona_de_01 <", value, "codigoPersonaDe1");
            return (Criteria) this;
        }

        public Criteria andCodigoPersonaDe1LessThanOrEqualTo(Integer value) {
            addCriterion("codigo_persona_de_01 <=", value, "codigoPersonaDe1");
            return (Criteria) this;
        }

        public Criteria andCodigoPersonaDe1In(List<Integer> values) {
            addCriterion("codigo_persona_de_01 in", values, "codigoPersonaDe1");
            return (Criteria) this;
        }

        public Criteria andCodigoPersonaDe1NotIn(List<Integer> values) {
            addCriterion("codigo_persona_de_01 not in", values, "codigoPersonaDe1");
            return (Criteria) this;
        }

        public Criteria andCodigoPersonaDe1Between(Integer value1, Integer value2) {
            addCriterion("codigo_persona_de_01 between", value1, value2, "codigoPersonaDe1");
            return (Criteria) this;
        }

        public Criteria andCodigoPersonaDe1NotBetween(Integer value1, Integer value2) {
            addCriterion("codigo_persona_de_01 not between", value1, value2, "codigoPersonaDe1");
            return (Criteria) this;
        }

        public Criteria andCodigoPersonaDe2IsNull() {
            addCriterion("codigo_persona_de_02 is null");
            return (Criteria) this;
        }

        public Criteria andCodigoPersonaDe2IsNotNull() {
            addCriterion("codigo_persona_de_02 is not null");
            return (Criteria) this;
        }

        public Criteria andCodigoPersonaDe2EqualTo(Integer value) {
            addCriterion("codigo_persona_de_02 =", value, "codigoPersonaDe2");
            return (Criteria) this;
        }

        public Criteria andCodigoPersonaDe2NotEqualTo(Integer value) {
            addCriterion("codigo_persona_de_02 <>", value, "codigoPersonaDe2");
            return (Criteria) this;
        }

        public Criteria andCodigoPersonaDe2GreaterThan(Integer value) {
            addCriterion("codigo_persona_de_02 >", value, "codigoPersonaDe2");
            return (Criteria) this;
        }

        public Criteria andCodigoPersonaDe2GreaterThanOrEqualTo(Integer value) {
            addCriterion("codigo_persona_de_02 >=", value, "codigoPersonaDe2");
            return (Criteria) this;
        }

        public Criteria andCodigoPersonaDe2LessThan(Integer value) {
            addCriterion("codigo_persona_de_02 <", value, "codigoPersonaDe2");
            return (Criteria) this;
        }

        public Criteria andCodigoPersonaDe2LessThanOrEqualTo(Integer value) {
            addCriterion("codigo_persona_de_02 <=", value, "codigoPersonaDe2");
            return (Criteria) this;
        }

        public Criteria andCodigoPersonaDe2In(List<Integer> values) {
            addCriterion("codigo_persona_de_02 in", values, "codigoPersonaDe2");
            return (Criteria) this;
        }

        public Criteria andCodigoPersonaDe2NotIn(List<Integer> values) {
            addCriterion("codigo_persona_de_02 not in", values, "codigoPersonaDe2");
            return (Criteria) this;
        }

        public Criteria andCodigoPersonaDe2Between(Integer value1, Integer value2) {
            addCriterion("codigo_persona_de_02 between", value1, value2, "codigoPersonaDe2");
            return (Criteria) this;
        }

        public Criteria andCodigoPersonaDe2NotBetween(Integer value1, Integer value2) {
            addCriterion("codigo_persona_de_02 not between", value1, value2, "codigoPersonaDe2");
            return (Criteria) this;
        }

        public Criteria andCodigoPersonaDe3IsNull() {
            addCriterion("codigo_persona_de_03 is null");
            return (Criteria) this;
        }

        public Criteria andCodigoPersonaDe3IsNotNull() {
            addCriterion("codigo_persona_de_03 is not null");
            return (Criteria) this;
        }

        public Criteria andCodigoPersonaDe3EqualTo(Integer value) {
            addCriterion("codigo_persona_de_03 =", value, "codigoPersonaDe3");
            return (Criteria) this;
        }

        public Criteria andCodigoPersonaDe3NotEqualTo(Integer value) {
            addCriterion("codigo_persona_de_03 <>", value, "codigoPersonaDe3");
            return (Criteria) this;
        }

        public Criteria andCodigoPersonaDe3GreaterThan(Integer value) {
            addCriterion("codigo_persona_de_03 >", value, "codigoPersonaDe3");
            return (Criteria) this;
        }

        public Criteria andCodigoPersonaDe3GreaterThanOrEqualTo(Integer value) {
            addCriterion("codigo_persona_de_03 >=", value, "codigoPersonaDe3");
            return (Criteria) this;
        }

        public Criteria andCodigoPersonaDe3LessThan(Integer value) {
            addCriterion("codigo_persona_de_03 <", value, "codigoPersonaDe3");
            return (Criteria) this;
        }

        public Criteria andCodigoPersonaDe3LessThanOrEqualTo(Integer value) {
            addCriterion("codigo_persona_de_03 <=", value, "codigoPersonaDe3");
            return (Criteria) this;
        }

        public Criteria andCodigoPersonaDe3In(List<Integer> values) {
            addCriterion("codigo_persona_de_03 in", values, "codigoPersonaDe3");
            return (Criteria) this;
        }

        public Criteria andCodigoPersonaDe3NotIn(List<Integer> values) {
            addCriterion("codigo_persona_de_03 not in", values, "codigoPersonaDe3");
            return (Criteria) this;
        }

        public Criteria andCodigoPersonaDe3Between(Integer value1, Integer value2) {
            addCriterion("codigo_persona_de_03 between", value1, value2, "codigoPersonaDe3");
            return (Criteria) this;
        }

        public Criteria andCodigoPersonaDe3NotBetween(Integer value1, Integer value2) {
            addCriterion("codigo_persona_de_03 not between", value1, value2, "codigoPersonaDe3");
            return (Criteria) this;
        }

        public Criteria andReferenciaIsNull() {
            addCriterion("referencia is null");
            return (Criteria) this;
        }

        public Criteria andReferenciaIsNotNull() {
            addCriterion("referencia is not null");
            return (Criteria) this;
        }

        public Criteria andReferenciaEqualTo(String value) {
            addCriterion("referencia =", value, "referencia");
            return (Criteria) this;
        }

        public Criteria andReferenciaNotEqualTo(String value) {
            addCriterion("referencia <>", value, "referencia");
            return (Criteria) this;
        }

        public Criteria andReferenciaGreaterThan(String value) {
            addCriterion("referencia >", value, "referencia");
            return (Criteria) this;
        }

        public Criteria andReferenciaGreaterThanOrEqualTo(String value) {
            addCriterion("referencia >=", value, "referencia");
            return (Criteria) this;
        }

        public Criteria andReferenciaLessThan(String value) {
            addCriterion("referencia <", value, "referencia");
            return (Criteria) this;
        }

        public Criteria andReferenciaLessThanOrEqualTo(String value) {
            addCriterion("referencia <=", value, "referencia");
            return (Criteria) this;
        }

        public Criteria andReferenciaLike(String value) {
            addCriterion("referencia like", value, "referencia");
            return (Criteria) this;
        }

        public Criteria andReferenciaNotLike(String value) {
            addCriterion("referencia not like", value, "referencia");
            return (Criteria) this;
        }

        public Criteria andReferenciaIn(List<String> values) {
            addCriterion("referencia in", values, "referencia");
            return (Criteria) this;
        }

        public Criteria andReferenciaNotIn(List<String> values) {
            addCriterion("referencia not in", values, "referencia");
            return (Criteria) this;
        }

        public Criteria andReferenciaBetween(String value1, String value2) {
            addCriterion("referencia between", value1, value2, "referencia");
            return (Criteria) this;
        }

        public Criteria andReferenciaNotBetween(String value1, String value2) {
            addCriterion("referencia not between", value1, value2, "referencia");
            return (Criteria) this;
        }

        public Criteria andFechaRegistroIsNull() {
            addCriterion("fecha_registro is null");
            return (Criteria) this;
        }

        public Criteria andFechaRegistroIsNotNull() {
            addCriterion("fecha_registro is not null");
            return (Criteria) this;
        }

        public Criteria andFechaRegistroEqualTo(Date value) {
            addCriterionForJDBCDate("fecha_registro =", value, "fechaRegistro");
            return (Criteria) this;
        }

        public Criteria andFechaRegistroNotEqualTo(Date value) {
            addCriterionForJDBCDate("fecha_registro <>", value, "fechaRegistro");
            return (Criteria) this;
        }

        public Criteria andFechaRegistroGreaterThan(Date value) {
            addCriterionForJDBCDate("fecha_registro >", value, "fechaRegistro");
            return (Criteria) this;
        }

        public Criteria andFechaRegistroGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("fecha_registro >=", value, "fechaRegistro");
            return (Criteria) this;
        }

        public Criteria andFechaRegistroLessThan(Date value) {
            addCriterionForJDBCDate("fecha_registro <", value, "fechaRegistro");
            return (Criteria) this;
        }

        public Criteria andFechaRegistroLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("fecha_registro <=", value, "fechaRegistro");
            return (Criteria) this;
        }

        public Criteria andFechaRegistroIn(List<Date> values) {
            addCriterionForJDBCDate("fecha_registro in", values, "fechaRegistro");
            return (Criteria) this;
        }

        public Criteria andFechaRegistroNotIn(List<Date> values) {
            addCriterionForJDBCDate("fecha_registro not in", values, "fechaRegistro");
            return (Criteria) this;
        }

        public Criteria andFechaRegistroBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("fecha_registro between", value1, value2, "fechaRegistro");
            return (Criteria) this;
        }

        public Criteria andFechaRegistroNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("fecha_registro not between", value1, value2, "fechaRegistro");
            return (Criteria) this;
        }

        public Criteria andFechaEnvioIsNull() {
            addCriterion("fecha_envio is null");
            return (Criteria) this;
        }

        public Criteria andFechaEnvioIsNotNull() {
            addCriterion("fecha_envio is not null");
            return (Criteria) this;
        }

        public Criteria andFechaEnvioEqualTo(Date value) {
            addCriterionForJDBCDate("fecha_envio =", value, "fechaEnvio");
            return (Criteria) this;
        }

        public Criteria andFechaEnvioNotEqualTo(Date value) {
            addCriterionForJDBCDate("fecha_envio <>", value, "fechaEnvio");
            return (Criteria) this;
        }

        public Criteria andFechaEnvioGreaterThan(Date value) {
            addCriterionForJDBCDate("fecha_envio >", value, "fechaEnvio");
            return (Criteria) this;
        }

        public Criteria andFechaEnvioGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("fecha_envio >=", value, "fechaEnvio");
            return (Criteria) this;
        }

        public Criteria andFechaEnvioLessThan(Date value) {
            addCriterionForJDBCDate("fecha_envio <", value, "fechaEnvio");
            return (Criteria) this;
        }

        public Criteria andFechaEnvioLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("fecha_envio <=", value, "fechaEnvio");
            return (Criteria) this;
        }

        public Criteria andFechaEnvioIn(List<Date> values) {
            addCriterionForJDBCDate("fecha_envio in", values, "fechaEnvio");
            return (Criteria) this;
        }

        public Criteria andFechaEnvioNotIn(List<Date> values) {
            addCriterionForJDBCDate("fecha_envio not in", values, "fechaEnvio");
            return (Criteria) this;
        }

        public Criteria andFechaEnvioBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("fecha_envio between", value1, value2, "fechaEnvio");
            return (Criteria) this;
        }

        public Criteria andFechaEnvioNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("fecha_envio not between", value1, value2, "fechaEnvio");
            return (Criteria) this;
        }

        public Criteria andDiagnosticoIsNull() {
            addCriterion("diagnostico is null");
            return (Criteria) this;
        }

        public Criteria andDiagnosticoIsNotNull() {
            addCriterion("diagnostico is not null");
            return (Criteria) this;
        }

        public Criteria andDiagnosticoEqualTo(String value) {
            addCriterion("diagnostico =", value, "diagnostico");
            return (Criteria) this;
        }

        public Criteria andDiagnosticoNotEqualTo(String value) {
            addCriterion("diagnostico <>", value, "diagnostico");
            return (Criteria) this;
        }

        public Criteria andDiagnosticoGreaterThan(String value) {
            addCriterion("diagnostico >", value, "diagnostico");
            return (Criteria) this;
        }

        public Criteria andDiagnosticoGreaterThanOrEqualTo(String value) {
            addCriterion("diagnostico >=", value, "diagnostico");
            return (Criteria) this;
        }

        public Criteria andDiagnosticoLessThan(String value) {
            addCriterion("diagnostico <", value, "diagnostico");
            return (Criteria) this;
        }

        public Criteria andDiagnosticoLessThanOrEqualTo(String value) {
            addCriterion("diagnostico <=", value, "diagnostico");
            return (Criteria) this;
        }

        public Criteria andDiagnosticoLike(String value) {
            addCriterion("diagnostico like", value, "diagnostico");
            return (Criteria) this;
        }

        public Criteria andDiagnosticoNotLike(String value) {
            addCriterion("diagnostico not like", value, "diagnostico");
            return (Criteria) this;
        }

        public Criteria andDiagnosticoIn(List<String> values) {
            addCriterion("diagnostico in", values, "diagnostico");
            return (Criteria) this;
        }

        public Criteria andDiagnosticoNotIn(List<String> values) {
            addCriterion("diagnostico not in", values, "diagnostico");
            return (Criteria) this;
        }

        public Criteria andDiagnosticoBetween(String value1, String value2) {
            addCriterion("diagnostico between", value1, value2, "diagnostico");
            return (Criteria) this;
        }

        public Criteria andDiagnosticoNotBetween(String value1, String value2) {
            addCriterion("diagnostico not between", value1, value2, "diagnostico");
            return (Criteria) this;
        }

        public Criteria andSugerenciasIsNull() {
            addCriterion("sugerencias is null");
            return (Criteria) this;
        }

        public Criteria andSugerenciasIsNotNull() {
            addCriterion("sugerencias is not null");
            return (Criteria) this;
        }

        public Criteria andSugerenciasEqualTo(String value) {
            addCriterion("sugerencias =", value, "sugerencias");
            return (Criteria) this;
        }

        public Criteria andSugerenciasNotEqualTo(String value) {
            addCriterion("sugerencias <>", value, "sugerencias");
            return (Criteria) this;
        }

        public Criteria andSugerenciasGreaterThan(String value) {
            addCriterion("sugerencias >", value, "sugerencias");
            return (Criteria) this;
        }

        public Criteria andSugerenciasGreaterThanOrEqualTo(String value) {
            addCriterion("sugerencias >=", value, "sugerencias");
            return (Criteria) this;
        }

        public Criteria andSugerenciasLessThan(String value) {
            addCriterion("sugerencias <", value, "sugerencias");
            return (Criteria) this;
        }

        public Criteria andSugerenciasLessThanOrEqualTo(String value) {
            addCriterion("sugerencias <=", value, "sugerencias");
            return (Criteria) this;
        }

        public Criteria andSugerenciasLike(String value) {
            addCriterion("sugerencias like", value, "sugerencias");
            return (Criteria) this;
        }

        public Criteria andSugerenciasNotLike(String value) {
            addCriterion("sugerencias not like", value, "sugerencias");
            return (Criteria) this;
        }

        public Criteria andSugerenciasIn(List<String> values) {
            addCriterion("sugerencias in", values, "sugerencias");
            return (Criteria) this;
        }

        public Criteria andSugerenciasNotIn(List<String> values) {
            addCriterion("sugerencias not in", values, "sugerencias");
            return (Criteria) this;
        }

        public Criteria andSugerenciasBetween(String value1, String value2) {
            addCriterion("sugerencias between", value1, value2, "sugerencias");
            return (Criteria) this;
        }

        public Criteria andSugerenciasNotBetween(String value1, String value2) {
            addCriterion("sugerencias not between", value1, value2, "sugerencias");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table informes
     *
     * @mbggenerated do_not_delete_during_merge Tue Mar 04 17:35:56 BOT 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table informes
     *
     * @mbggenerated Tue Mar 04 17:35:56 BOT 2014
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}