package org.quarkbit.trabajosocialsanjuan.dao.domain;

import java.util.Date;

public class InformeDetalle {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column informes_detalle.codigo_informe
     *
     * @mbggenerated Tue Mar 04 17:35:57 BOT 2014
     */
    private Integer codigoInforme;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column informes_detalle.referencia_caso
     *
     * @mbggenerated Tue Mar 04 17:35:57 BOT 2014
     */
    private String referenciaCaso;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column informes_detalle.fecha_inicio
     *
     * @mbggenerated Tue Mar 04 17:35:57 BOT 2014
     */
    private Date fechaInicio;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column informes_detalle.fecha_fin
     *
     * @mbggenerated Tue Mar 04 17:35:57 BOT 2014
     */
    private Date fechaFin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column informes_detalle.situacion_habitacional
     *
     * @mbggenerated Tue Mar 04 17:35:57 BOT 2014
     */
    private String situacionHabitacional;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column informes_detalle.integracion_familiar
     *
     * @mbggenerated Tue Mar 04 17:35:57 BOT 2014
     */
    private String integracionFamiliar;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column informes_detalle.desarrollo_afectivo
     *
     * @mbggenerated Tue Mar 04 17:35:57 BOT 2014
     */
    private String desarrolloAfectivo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column informes_detalle.historia_social
     *
     * @mbggenerated Tue Mar 04 17:35:57 BOT 2014
     */
    private String historiaSocial;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column informes_detalle.situacion_actual
     *
     * @mbggenerated Tue Mar 04 17:35:57 BOT 2014
     */
    private String situacionActual;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column informes_detalle.fuentes_informacion
     *
     * @mbggenerated Tue Mar 04 17:35:57 BOT 2014
     */
    private String fuentesInformacion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column informes_detalle.descripcion_caso
     *
     * @mbggenerated Tue Mar 04 17:35:57 BOT 2014
     */
    private String descripcionCaso;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column informes_detalle.documentos_adjuntos
     *
     * @mbggenerated Tue Mar 04 17:35:57 BOT 2014
     */
    private String documentosAdjuntos;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column informes_detalle.codigo_informe
     *
     * @return the value of informes_detalle.codigo_informe
     *
     * @mbggenerated Tue Mar 04 17:35:57 BOT 2014
     */
    public Integer getCodigoInforme() {
        return codigoInforme;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column informes_detalle.codigo_informe
     *
     * @param codigoInforme the value for informes_detalle.codigo_informe
     *
     * @mbggenerated Tue Mar 04 17:35:57 BOT 2014
     */
    public void setCodigoInforme(Integer codigoInforme) {
        this.codigoInforme = codigoInforme;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column informes_detalle.referencia_caso
     *
     * @return the value of informes_detalle.referencia_caso
     *
     * @mbggenerated Tue Mar 04 17:35:57 BOT 2014
     */
    public String getReferenciaCaso() {
        return referenciaCaso;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column informes_detalle.referencia_caso
     *
     * @param referenciaCaso the value for informes_detalle.referencia_caso
     *
     * @mbggenerated Tue Mar 04 17:35:57 BOT 2014
     */
    public void setReferenciaCaso(String referenciaCaso) {
        this.referenciaCaso = referenciaCaso == null ? null : referenciaCaso.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column informes_detalle.fecha_inicio
     *
     * @return the value of informes_detalle.fecha_inicio
     *
     * @mbggenerated Tue Mar 04 17:35:57 BOT 2014
     */
    public Date getFechaInicio() {
        return fechaInicio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column informes_detalle.fecha_inicio
     *
     * @param fechaInicio the value for informes_detalle.fecha_inicio
     *
     * @mbggenerated Tue Mar 04 17:35:57 BOT 2014
     */
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column informes_detalle.fecha_fin
     *
     * @return the value of informes_detalle.fecha_fin
     *
     * @mbggenerated Tue Mar 04 17:35:57 BOT 2014
     */
    public Date getFechaFin() {
        return fechaFin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column informes_detalle.fecha_fin
     *
     * @param fechaFin the value for informes_detalle.fecha_fin
     *
     * @mbggenerated Tue Mar 04 17:35:57 BOT 2014
     */
    public void setFechaFin(Date fechaFin) {
        this.fechaFin = fechaFin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column informes_detalle.situacion_habitacional
     *
     * @return the value of informes_detalle.situacion_habitacional
     *
     * @mbggenerated Tue Mar 04 17:35:57 BOT 2014
     */
    public String getSituacionHabitacional() {
        return situacionHabitacional;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column informes_detalle.situacion_habitacional
     *
     * @param situacionHabitacional the value for informes_detalle.situacion_habitacional
     *
     * @mbggenerated Tue Mar 04 17:35:57 BOT 2014
     */
    public void setSituacionHabitacional(String situacionHabitacional) {
        this.situacionHabitacional = situacionHabitacional == null ? null : situacionHabitacional.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column informes_detalle.integracion_familiar
     *
     * @return the value of informes_detalle.integracion_familiar
     *
     * @mbggenerated Tue Mar 04 17:35:57 BOT 2014
     */
    public String getIntegracionFamiliar() {
        return integracionFamiliar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column informes_detalle.integracion_familiar
     *
     * @param integracionFamiliar the value for informes_detalle.integracion_familiar
     *
     * @mbggenerated Tue Mar 04 17:35:57 BOT 2014
     */
    public void setIntegracionFamiliar(String integracionFamiliar) {
        this.integracionFamiliar = integracionFamiliar == null ? null : integracionFamiliar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column informes_detalle.desarrollo_afectivo
     *
     * @return the value of informes_detalle.desarrollo_afectivo
     *
     * @mbggenerated Tue Mar 04 17:35:57 BOT 2014
     */
    public String getDesarrolloAfectivo() {
        return desarrolloAfectivo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column informes_detalle.desarrollo_afectivo
     *
     * @param desarrolloAfectivo the value for informes_detalle.desarrollo_afectivo
     *
     * @mbggenerated Tue Mar 04 17:35:57 BOT 2014
     */
    public void setDesarrolloAfectivo(String desarrolloAfectivo) {
        this.desarrolloAfectivo = desarrolloAfectivo == null ? null : desarrolloAfectivo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column informes_detalle.historia_social
     *
     * @return the value of informes_detalle.historia_social
     *
     * @mbggenerated Tue Mar 04 17:35:57 BOT 2014
     */
    public String getHistoriaSocial() {
        return historiaSocial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column informes_detalle.historia_social
     *
     * @param historiaSocial the value for informes_detalle.historia_social
     *
     * @mbggenerated Tue Mar 04 17:35:57 BOT 2014
     */
    public void setHistoriaSocial(String historiaSocial) {
        this.historiaSocial = historiaSocial == null ? null : historiaSocial.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column informes_detalle.situacion_actual
     *
     * @return the value of informes_detalle.situacion_actual
     *
     * @mbggenerated Tue Mar 04 17:35:57 BOT 2014
     */
    public String getSituacionActual() {
        return situacionActual;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column informes_detalle.situacion_actual
     *
     * @param situacionActual the value for informes_detalle.situacion_actual
     *
     * @mbggenerated Tue Mar 04 17:35:57 BOT 2014
     */
    public void setSituacionActual(String situacionActual) {
        this.situacionActual = situacionActual == null ? null : situacionActual.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column informes_detalle.fuentes_informacion
     *
     * @return the value of informes_detalle.fuentes_informacion
     *
     * @mbggenerated Tue Mar 04 17:35:57 BOT 2014
     */
    public String getFuentesInformacion() {
        return fuentesInformacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column informes_detalle.fuentes_informacion
     *
     * @param fuentesInformacion the value for informes_detalle.fuentes_informacion
     *
     * @mbggenerated Tue Mar 04 17:35:57 BOT 2014
     */
    public void setFuentesInformacion(String fuentesInformacion) {
        this.fuentesInformacion = fuentesInformacion == null ? null : fuentesInformacion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column informes_detalle.descripcion_caso
     *
     * @return the value of informes_detalle.descripcion_caso
     *
     * @mbggenerated Tue Mar 04 17:35:57 BOT 2014
     */
    public String getDescripcionCaso() {
        return descripcionCaso;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column informes_detalle.descripcion_caso
     *
     * @param descripcionCaso the value for informes_detalle.descripcion_caso
     *
     * @mbggenerated Tue Mar 04 17:35:57 BOT 2014
     */
    public void setDescripcionCaso(String descripcionCaso) {
        this.descripcionCaso = descripcionCaso == null ? null : descripcionCaso.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column informes_detalle.documentos_adjuntos
     *
     * @return the value of informes_detalle.documentos_adjuntos
     *
     * @mbggenerated Tue Mar 04 17:35:57 BOT 2014
     */
    public String getDocumentosAdjuntos() {
        return documentosAdjuntos;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column informes_detalle.documentos_adjuntos
     *
     * @param documentosAdjuntos the value for informes_detalle.documentos_adjuntos
     *
     * @mbggenerated Tue Mar 04 17:35:57 BOT 2014
     */
    public void setDocumentosAdjuntos(String documentosAdjuntos) {
        this.documentosAdjuntos = documentosAdjuntos == null ? null : documentosAdjuntos.trim();
    }
}