package org.quarkbit.trabajosocialsanjuan.dao.domain;

public class PropiedadHistorialClinico {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column propiedades_historial_clinico.numero_propiedad
     *
     * @mbggenerated Sun Apr 13 16:11:45 CEST 2014
     */
    private Integer numeroPropiedad;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column propiedades_historial_clinico.numero_propiedad_tipo
     *
     * @mbggenerated Sun Apr 13 16:11:45 CEST 2014
     */
    private Integer numeroPropiedadTipo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column propiedades_historial_clinico.nombre_propiedad
     *
     * @mbggenerated Sun Apr 13 16:11:45 CEST 2014
     */
    private String nombrePropiedad;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column propiedades_historial_clinico.abreviacion
     *
     * @mbggenerated Sun Apr 13 16:11:45 CEST 2014
     */
    private String abreviacion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column propiedades_historial_clinico.composicion
     *
     * @mbggenerated Sun Apr 13 16:11:45 CEST 2014
     */
    private String composicion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column propiedades_historial_clinico.descripcion
     *
     * @mbggenerated Sun Apr 13 16:11:45 CEST 2014
     */
    private String descripcion;

    private PropiedadTipo propiedadTipo;
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column propiedades_historial_clinico.numero_propiedad
     *
     * @return the value of propiedades_historial_clinico.numero_propiedad
     *
     * @mbggenerated Sun Apr 13 16:11:45 CEST 2014
     */
    public Integer getNumeroPropiedad() {
        return numeroPropiedad;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column propiedades_historial_clinico.numero_propiedad
     *
     * @param numeroPropiedad the value for propiedades_historial_clinico.numero_propiedad
     *
     * @mbggenerated Sun Apr 13 16:11:45 CEST 2014
     */
    public void setNumeroPropiedad(Integer numeroPropiedad) {
        this.numeroPropiedad = numeroPropiedad;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column propiedades_historial_clinico.numero_propiedad_tipo
     *
     * @return the value of propiedades_historial_clinico.numero_propiedad_tipo
     *
     * @mbggenerated Sun Apr 13 16:11:45 CEST 2014
     */
    public Integer getNumeroPropiedadTipo() {
        return numeroPropiedadTipo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column propiedades_historial_clinico.numero_propiedad_tipo
     *
     * @param numeroPropiedadTipo the value for propiedades_historial_clinico.numero_propiedad_tipo
     *
     * @mbggenerated Sun Apr 13 16:11:45 CEST 2014
     */
    public void setNumeroPropiedadTipo(Integer numeroPropiedadTipo) {
        this.numeroPropiedadTipo = numeroPropiedadTipo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column propiedades_historial_clinico.nombre_propiedad
     *
     * @return the value of propiedades_historial_clinico.nombre_propiedad
     *
     * @mbggenerated Sun Apr 13 16:11:45 CEST 2014
     */
    public String getNombrePropiedad() {
        return nombrePropiedad;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column propiedades_historial_clinico.nombre_propiedad
     *
     * @param nombrePropiedad the value for propiedades_historial_clinico.nombre_propiedad
     *
     * @mbggenerated Sun Apr 13 16:11:45 CEST 2014
     */
    public void setNombrePropiedad(String nombrePropiedad) {
        this.nombrePropiedad = nombrePropiedad == null ? null : nombrePropiedad.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column propiedades_historial_clinico.abreviacion
     *
     * @return the value of propiedades_historial_clinico.abreviacion
     *
     * @mbggenerated Sun Apr 13 16:11:45 CEST 2014
     */
    public String getAbreviacion() {
        return abreviacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column propiedades_historial_clinico.abreviacion
     *
     * @param abreviacion the value for propiedades_historial_clinico.abreviacion
     *
     * @mbggenerated Sun Apr 13 16:11:45 CEST 2014
     */
    public void setAbreviacion(String abreviacion) {
        this.abreviacion = abreviacion == null ? null : abreviacion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column propiedades_historial_clinico.composicion
     *
     * @return the value of propiedades_historial_clinico.composicion
     *
     * @mbggenerated Sun Apr 13 16:11:45 CEST 2014
     */
    public String getComposicion() {
        return composicion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column propiedades_historial_clinico.composicion
     *
     * @param composicion the value for propiedades_historial_clinico.composicion
     *
     * @mbggenerated Sun Apr 13 16:11:45 CEST 2014
     */
    public void setComposicion(String composicion) {
        this.composicion = composicion == null ? null : composicion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column propiedades_historial_clinico.descripcion
     *
     * @return the value of propiedades_historial_clinico.descripcion
     *
     * @mbggenerated Sun Apr 13 16:11:45 CEST 2014
     */
    public String getDescripcion() {
        return descripcion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column propiedades_historial_clinico.descripcion
     *
     * @param descripcion the value for propiedades_historial_clinico.descripcion
     *
     * @mbggenerated Sun Apr 13 16:11:45 CEST 2014
     */
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion == null ? null : descripcion.trim();
    }

	public PropiedadTipo getPropiedadTipo() {
		return propiedadTipo;
	}

	public void setPropiedadTipo(PropiedadTipo propiedadTipo) {
		this.propiedadTipo = propiedadTipo;
	}

	@Override
	public String toString() {
		return nombrePropiedad;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((nombrePropiedad == null) ? 0 : nombrePropiedad.hashCode());
		result = prime * result
				+ ((numeroPropiedad == null) ? 0 : numeroPropiedad.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		PropiedadHistorialClinico other = (PropiedadHistorialClinico) obj;
		if (nombrePropiedad == null) {
			if (other.nombrePropiedad != null)
				return false;
		} else if (!nombrePropiedad.equals(other.nombrePropiedad))
			return false;
		if (numeroPropiedad == null) {
			if (other.numeroPropiedad != null)
				return false;
		} else if (!numeroPropiedad.equals(other.numeroPropiedad))
			return false;
		return true;
	}
	
	
}