package org.quarkbit.trabajosocialsanjuan.dao.domain;

import java.util.Date;

public class Usuario {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usuarios.codigo_usuario
     *
     * @mbggenerated Tue Feb 11 16:49:30 BOT 2014
     */
    private Integer codigoUsuario;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usuarios.codigo_persona
     *
     * @mbggenerated Tue Feb 11 16:49:30 BOT 2014
     */
    private Integer codigoPersona;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usuarios.fecha_registro
     *
     * @mbggenerated Tue Feb 11 16:49:30 BOT 2014
     */
    private Date fechaRegistro;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usuarios.nombre_usuario
     *
     * @mbggenerated Tue Feb 11 16:49:30 BOT 2014
     */
    private String nombreUsuario;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usuarios.contrasenia
     *
     * @mbggenerated Tue Feb 11 16:49:30 BOT 2014
     */
    private String contrasenia;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usuarios.codigo_tipo
     *
     * @mbggenerated Tue Feb 11 16:49:30 BOT 2014
     */
    private String codigoTipo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usuarios.codigo_institucion
     *
     * @mbggenerated Tue Feb 11 16:49:30 BOT 2014
     */
    private Integer codigoInstitucion;
    
    
    private Persona persona;
    private Institucion institucion;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usuarios.codigo_usuario
     *
     * @return the value of usuarios.codigo_usuario
     *
     * @mbggenerated Tue Feb 11 16:49:30 BOT 2014
     */
    public Integer getCodigoUsuario() {
        return codigoUsuario;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usuarios.codigo_usuario
     *
     * @param codigoUsuario the value for usuarios.codigo_usuario
     *
     * @mbggenerated Tue Feb 11 16:49:30 BOT 2014
     */
    public void setCodigoUsuario(Integer codigoUsuario) {
        this.codigoUsuario = codigoUsuario;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usuarios.codigo_persona
     *
     * @return the value of usuarios.codigo_persona
     *
     * @mbggenerated Tue Feb 11 16:49:30 BOT 2014
     */
    public Integer getCodigoPersona() {
        return codigoPersona;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usuarios.codigo_persona
     *
     * @param codigoPersona the value for usuarios.codigo_persona
     *
     * @mbggenerated Tue Feb 11 16:49:30 BOT 2014
     */
    public void setCodigoPersona(Integer codigoPersona) {
        this.codigoPersona = codigoPersona;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usuarios.fecha_registro
     *
     * @return the value of usuarios.fecha_registro
     *
     * @mbggenerated Tue Feb 11 16:49:30 BOT 2014
     */
    public Date getFechaRegistro() {
        return fechaRegistro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usuarios.fecha_registro
     *
     * @param fechaRegistro the value for usuarios.fecha_registro
     *
     * @mbggenerated Tue Feb 11 16:49:30 BOT 2014
     */
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usuarios.nombre_usuario
     *
     * @return the value of usuarios.nombre_usuario
     *
     * @mbggenerated Tue Feb 11 16:49:30 BOT 2014
     */
    public String getNombreUsuario() {
        return nombreUsuario;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usuarios.nombre_usuario
     *
     * @param nombreUsuario the value for usuarios.nombre_usuario
     *
     * @mbggenerated Tue Feb 11 16:49:30 BOT 2014
     */
    public void setNombreUsuario(String nombreUsuario) {
        this.nombreUsuario = nombreUsuario == null ? null : nombreUsuario.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usuarios.contrasenia
     *
     * @return the value of usuarios.contrasenia
     *
     * @mbggenerated Tue Feb 11 16:49:30 BOT 2014
     */
    public String getContrasenia() {
        return contrasenia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usuarios.contrasenia
     *
     * @param contrasenia the value for usuarios.contrasenia
     *
     * @mbggenerated Tue Feb 11 16:49:30 BOT 2014
     */
    public void setContrasenia(String contrasenia) {
        this.contrasenia = contrasenia == null ? null : contrasenia.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usuarios.codigo_tipo
     *
     * @return the value of usuarios.codigo_tipo
     *
     * @mbggenerated Tue Feb 11 16:49:30 BOT 2014
     */
    public String getCodigoTipo() {
        return codigoTipo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usuarios.codigo_tipo
     *
     * @param codigoTipo the value for usuarios.codigo_tipo
     *
     * @mbggenerated Tue Feb 11 16:49:30 BOT 2014
     */
    public void setCodigoTipo(String codigoTipo) {
        this.codigoTipo = codigoTipo == null ? null : codigoTipo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usuarios.codigo_institucion
     *
     * @return the value of usuarios.codigo_institucion
     *
     * @mbggenerated Tue Feb 11 16:49:30 BOT 2014
     */
    public Integer getCodigoInstitucion() {
        return codigoInstitucion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usuarios.codigo_institucion
     *
     * @param codigoInstitucion the value for usuarios.codigo_institucion
     *
     * @mbggenerated Tue Feb 11 16:49:30 BOT 2014
     */
    public void setCodigoInstitucion(Integer codigoInstitucion) {
        this.codigoInstitucion = codigoInstitucion;
    }

	public Persona getPersona() {
		return persona;
	}

	public void setPersona(Persona persona) {
		this.persona = persona;
	}
	
	public String getTipo()
	{
		//'S'::bpchar, 'M'::bpchar, 'V'::bpchar, 'A'
		switch (this.codigoTipo) {
		case "S":
			return "SECRETARIA";
		case "M":
			return "MEDICO(A)";
		case "V":
			return "VISITADORA SOCIAL";
		case "A":
			return "ADMINISTRADOR(A)";
		case "P":
			return "PSICOLOGO(A)";
		case "D":
			return "DIRECTOR(A)";
		default:
			return null;
		}
	}
	
	public void setTipo(String tipo)
	{
		switch (tipo) {
		case "PSICOLOGO(A)":
			this.codigoTipo = "P";
			break;
		case "MEDICO(A)":
			this.codigoTipo = "M";
			break;
		case "VISITADORA SOCIAL":
			this.codigoTipo = "V";
			break;
		case "ADMINISTRADOR(A)":
			this.codigoTipo = "A";
			break;
		case "SECRETARIA":
			this.codigoTipo = "S";
			break;
		case "DIRECTOR(A)":
			this.codigoTipo = "D";
			break;
		default:
			break;
		}
	}

	public Institucion getInstitucion() {
		return institucion;
	}

	public void setInstitucion(Institucion institucion) {
		this.institucion = institucion;
	}
}

