package org.quarkbit.trabajosocialsanjuan.dao.persistence;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;
import org.quarkbit.trabajosocialsanjuan.dao.domain.Consulta;
import org.quarkbit.trabajosocialsanjuan.dao.domain.ConsultaExample;

public interface ConsultaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consulta
     *
     * @mbggenerated Sun Apr 13 16:11:45 CEST 2014
     */
    int countByExample(ConsultaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consulta
     *
     * @mbggenerated Sun Apr 13 16:11:45 CEST 2014
     */
    int deleteByExample(ConsultaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consulta
     *
     * @mbggenerated Sun Apr 13 16:11:45 CEST 2014
     */
    int deleteByPrimaryKey(Integer numeroConsulta);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consulta
     *
     * @mbggenerated Sun Apr 13 16:11:45 CEST 2014
     */
    int insert(Consulta record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consulta
     *
     * @mbggenerated Sun Apr 13 16:11:45 CEST 2014
     */
    int insertSelective(Consulta record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consulta
     *
     * @mbggenerated Sun Apr 13 16:11:45 CEST 2014
     */
    List<Consulta> selectByExample(ConsultaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consulta
     *
     * @mbggenerated Sun Apr 13 16:11:45 CEST 2014
     */
    Consulta selectByPrimaryKey(Integer numeroConsulta);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consulta
     *
     * @mbggenerated Sun Apr 13 16:11:45 CEST 2014
     */
    int updateByExampleSelective(@Param("record") Consulta record, @Param("example") ConsultaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consulta
     *
     * @mbggenerated Sun Apr 13 16:11:45 CEST 2014
     */
    int updateByExample(@Param("record") Consulta record, @Param("example") ConsultaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consulta
     *
     * @mbggenerated Sun Apr 13 16:11:45 CEST 2014
     */
    int updateByPrimaryKeySelective(Consulta record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consulta
     *
     * @mbggenerated Sun Apr 13 16:11:45 CEST 2014
     */
    int updateByPrimaryKey(Consulta record);
    
    public int obtenerUltimoId(Map<String, Integer> dato);
    
}