package org.quarkbit.trabajosocialsanjuan.dao.persistence;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;
import org.quarkbit.trabajosocialsanjuan.dao.domain.HistorialClinico;
import org.quarkbit.trabajosocialsanjuan.dao.domain.HistorialClinicoExample;

public interface HistorialClinicoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table historia_clinico
     *
     * @mbggenerated Sun Apr 13 16:11:45 CEST 2014
     */
    int countByExample(HistorialClinicoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table historia_clinico
     *
     * @mbggenerated Sun Apr 13 16:11:45 CEST 2014
     */
    int deleteByExample(HistorialClinicoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table historia_clinico
     *
     * @mbggenerated Sun Apr 13 16:11:45 CEST 2014
     */
    int deleteByPrimaryKey(Integer numeroHistorialClinico);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table historia_clinico
     *
     * @mbggenerated Sun Apr 13 16:11:45 CEST 2014
     */
    int insert(HistorialClinico record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table historia_clinico
     *
     * @mbggenerated Sun Apr 13 16:11:45 CEST 2014
     */
    int insertSelective(HistorialClinico record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table historia_clinico
     *
     * @mbggenerated Sun Apr 13 16:11:45 CEST 2014
     */
    List<HistorialClinico> selectByExample(HistorialClinicoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table historia_clinico
     *
     * @mbggenerated Sun Apr 13 16:11:45 CEST 2014
     */
    HistorialClinico selectByPrimaryKey(Integer numeroHistorialClinico);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table historia_clinico
     *
     * @mbggenerated Sun Apr 13 16:11:45 CEST 2014
     */
    int updateByExampleSelective(@Param("record") HistorialClinico record, @Param("example") HistorialClinicoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table historia_clinico
     *
     * @mbggenerated Sun Apr 13 16:11:45 CEST 2014
     */
    int updateByExample(@Param("record") HistorialClinico record, @Param("example") HistorialClinicoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table historia_clinico
     *
     * @mbggenerated Sun Apr 13 16:11:45 CEST 2014
     */
    int updateByPrimaryKeySelective(HistorialClinico record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table historia_clinico
     *
     * @mbggenerated Sun Apr 13 16:11:45 CEST 2014
     */
    int updateByPrimaryKey(HistorialClinico record);
    public int obtenerUltimoId(Map<String, Integer> dato);
}