package org.quarkbit.trabajosocialsanjuan.dao.persistence;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.quarkbit.trabajosocialsanjuan.dao.domain.InformeDetalle;
import org.quarkbit.trabajosocialsanjuan.dao.domain.InformeDetalleExample;

public interface InformeDetalleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table informes_detalle
     *
     * @mbggenerated Tue Mar 04 17:35:57 BOT 2014
     */
    int countByExample(InformeDetalleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table informes_detalle
     *
     * @mbggenerated Tue Mar 04 17:35:57 BOT 2014
     */
    int deleteByExample(InformeDetalleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table informes_detalle
     *
     * @mbggenerated Tue Mar 04 17:35:57 BOT 2014
     */
    int deleteByPrimaryKey(Integer codigoInforme);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table informes_detalle
     *
     * @mbggenerated Tue Mar 04 17:35:57 BOT 2014
     */
    int insert(InformeDetalle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table informes_detalle
     *
     * @mbggenerated Tue Mar 04 17:35:57 BOT 2014
     */
    int insertSelective(InformeDetalle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table informes_detalle
     *
     * @mbggenerated Tue Mar 04 17:35:57 BOT 2014
     */
    List<InformeDetalle> selectByExample(InformeDetalleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table informes_detalle
     *
     * @mbggenerated Tue Mar 04 17:35:57 BOT 2014
     */
    InformeDetalle selectByPrimaryKey(Integer codigoInforme);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table informes_detalle
     *
     * @mbggenerated Tue Mar 04 17:35:57 BOT 2014
     */
    int updateByExampleSelective(@Param("record") InformeDetalle record, @Param("example") InformeDetalleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table informes_detalle
     *
     * @mbggenerated Tue Mar 04 17:35:57 BOT 2014
     */
    int updateByExample(@Param("record") InformeDetalle record, @Param("example") InformeDetalleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table informes_detalle
     *
     * @mbggenerated Tue Mar 04 17:35:57 BOT 2014
     */
    int updateByPrimaryKeySelective(InformeDetalle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table informes_detalle
     *
     * @mbggenerated Tue Mar 04 17:35:57 BOT 2014
     */
    int updateByPrimaryKey(InformeDetalle record);
}