package org.quarkbit.trabajosocialsanjuan.dao.persistence;

import java.util.Date;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;
import org.quarkbit.trabajosocialsanjuan.dao.domain.Ingreso;
import org.quarkbit.trabajosocialsanjuan.dao.domain.IngresoExample;

public interface IngresoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ingresos
     *
     * @mbggenerated Thu Mar 20 09:56:36 BOT 2014
     */
    int countByExample(IngresoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ingresos
     *
     * @mbggenerated Thu Mar 20 09:56:36 BOT 2014
     */
    int deleteByExample(IngresoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ingresos
     *
     * @mbggenerated Thu Mar 20 09:56:36 BOT 2014
     */
    int deleteByPrimaryKey(Integer codigoIngreso);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ingresos
     *
     * @mbggenerated Thu Mar 20 09:56:36 BOT 2014
     */
    int insert(Ingreso record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ingresos
     *
     * @mbggenerated Thu Mar 20 09:56:36 BOT 2014
     */
    int insertSelective(Ingreso record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ingresos
     *
     * @mbggenerated Thu Mar 20 09:56:36 BOT 2014
     */
    List<Ingreso> selectByExample(IngresoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ingresos
     *
     * @mbggenerated Thu Mar 20 09:56:36 BOT 2014
     */
    Ingreso selectByPrimaryKey(Integer codigoIngreso);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ingresos
     *
     * @mbggenerated Thu Mar 20 09:56:36 BOT 2014
     */
    int updateByExampleSelective(@Param("record") Ingreso record, @Param("example") IngresoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ingresos
     *
     * @mbggenerated Thu Mar 20 09:56:36 BOT 2014
     */
    int updateByExample(@Param("record") Ingreso record, @Param("example") IngresoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ingresos
     *
     * @mbggenerated Thu Mar 20 09:56:36 BOT 2014
     */
    int updateByPrimaryKeySelective(Ingreso record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ingresos
     *
     * @mbggenerated Thu Mar 20 09:56:36 BOT 2014
     */
    int updateByPrimaryKey(Ingreso record);
    
    public int obtenerUltimoId(Map<String, Integer> dato);

	int obtenerFechaHoraServidor(Map<String, Date> mapa);

}