package org.quarkbit.trabajosocialsanjuan.dao.persistence;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;
import org.quarkbit.trabajosocialsanjuan.dao.domain.PropiedadHistorialClinico;
import org.quarkbit.trabajosocialsanjuan.dao.domain.PropiedadHistorialClinicoExample;

public interface PropiedadHistorialClinicoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table propiedades_historial_clinico
     *
     * @mbggenerated Sun Apr 13 16:11:45 CEST 2014
     */
    int countByExample(PropiedadHistorialClinicoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table propiedades_historial_clinico
     *
     * @mbggenerated Sun Apr 13 16:11:45 CEST 2014
     */
    int deleteByExample(PropiedadHistorialClinicoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table propiedades_historial_clinico
     *
     * @mbggenerated Sun Apr 13 16:11:45 CEST 2014
     */
    int deleteByPrimaryKey(Integer numeroPropiedad);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table propiedades_historial_clinico
     *
     * @mbggenerated Sun Apr 13 16:11:45 CEST 2014
     */
    int insert(PropiedadHistorialClinico record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table propiedades_historial_clinico
     *
     * @mbggenerated Sun Apr 13 16:11:45 CEST 2014
     */
    int insertSelective(PropiedadHistorialClinico record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table propiedades_historial_clinico
     *
     * @mbggenerated Sun Apr 13 16:11:45 CEST 2014
     */
    List<PropiedadHistorialClinico> selectByExample(PropiedadHistorialClinicoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table propiedades_historial_clinico
     *
     * @mbggenerated Sun Apr 13 16:11:45 CEST 2014
     */
    PropiedadHistorialClinico selectByPrimaryKey(Integer numeroPropiedad);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table propiedades_historial_clinico
     *
     * @mbggenerated Sun Apr 13 16:11:45 CEST 2014
     */
    int updateByExampleSelective(@Param("record") PropiedadHistorialClinico record, @Param("example") PropiedadHistorialClinicoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table propiedades_historial_clinico
     *
     * @mbggenerated Sun Apr 13 16:11:45 CEST 2014
     */
    int updateByExample(@Param("record") PropiedadHistorialClinico record, @Param("example") PropiedadHistorialClinicoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table propiedades_historial_clinico
     *
     * @mbggenerated Sun Apr 13 16:11:45 CEST 2014
     */
    int updateByPrimaryKeySelective(PropiedadHistorialClinico record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table propiedades_historial_clinico
     *
     * @mbggenerated Sun Apr 13 16:11:45 CEST 2014
     */
    int updateByPrimaryKey(PropiedadHistorialClinico record);
    public int obtenerUltimoId(Map<String, Integer> dato);
}