package org.quarkbit.trabajosocialsanjuan.dao.persistence;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;
import org.quarkbit.trabajosocialsanjuan.dao.domain.PropiedadTipo;
import org.quarkbit.trabajosocialsanjuan.dao.domain.PropiedadTipoExample;

public interface PropiedadTipoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table propiedades_tipos
     *
     * @mbggenerated Sun Apr 13 16:11:45 CEST 2014
     */
    int countByExample(PropiedadTipoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table propiedades_tipos
     *
     * @mbggenerated Sun Apr 13 16:11:45 CEST 2014
     */
    int deleteByExample(PropiedadTipoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table propiedades_tipos
     *
     * @mbggenerated Sun Apr 13 16:11:45 CEST 2014
     */
    int deleteByPrimaryKey(Integer numeroPropiedadTipo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table propiedades_tipos
     *
     * @mbggenerated Sun Apr 13 16:11:45 CEST 2014
     */
    int insert(PropiedadTipo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table propiedades_tipos
     *
     * @mbggenerated Sun Apr 13 16:11:45 CEST 2014
     */
    int insertSelective(PropiedadTipo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table propiedades_tipos
     *
     * @mbggenerated Sun Apr 13 16:11:45 CEST 2014
     */
    List<PropiedadTipo> selectByExample(PropiedadTipoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table propiedades_tipos
     *
     * @mbggenerated Sun Apr 13 16:11:45 CEST 2014
     */
    PropiedadTipo selectByPrimaryKey(Integer numeroPropiedadTipo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table propiedades_tipos
     *
     * @mbggenerated Sun Apr 13 16:11:45 CEST 2014
     */
    int updateByExampleSelective(@Param("record") PropiedadTipo record, @Param("example") PropiedadTipoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table propiedades_tipos
     *
     * @mbggenerated Sun Apr 13 16:11:45 CEST 2014
     */
    int updateByExample(@Param("record") PropiedadTipo record, @Param("example") PropiedadTipoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table propiedades_tipos
     *
     * @mbggenerated Sun Apr 13 16:11:45 CEST 2014
     */
    int updateByPrimaryKeySelective(PropiedadTipo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table propiedades_tipos
     *
     * @mbggenerated Sun Apr 13 16:11:45 CEST 2014
     */
    int updateByPrimaryKey(PropiedadTipo record);
    public int obtenerUltimoId(Map<String, Integer> dato);
}