package org.quarkbit.trabajosocialsanjuan.dao.persistence;

import java.util.Date;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;
import org.quarkbit.trabajosocialsanjuan.dao.domain.Usuario;
import org.quarkbit.trabajosocialsanjuan.dao.domain.UsuarioExample;

public interface UsuarioMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usuarios
     *
     * @mbggenerated Tue Feb 11 16:49:30 BOT 2014
     */
    int countByExample(UsuarioExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usuarios
     *
     * @mbggenerated Tue Feb 11 16:49:30 BOT 2014
     */
    int deleteByExample(UsuarioExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usuarios
     *
     * @mbggenerated Tue Feb 11 16:49:30 BOT 2014
     */
    int deleteByPrimaryKey(Integer codigoUsuario);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usuarios
     *
     * @mbggenerated Tue Feb 11 16:49:30 BOT 2014
     */
    int insert(Usuario record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usuarios
     *
     * @mbggenerated Tue Feb 11 16:49:30 BOT 2014
     */
    int insertSelective(Usuario record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usuarios
     *
     * @mbggenerated Tue Feb 11 16:49:30 BOT 2014
     */
    List<Usuario> selectByExample(UsuarioExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usuarios
     *
     * @mbggenerated Tue Feb 11 16:49:30 BOT 2014
     */
    Usuario selectByPrimaryKey(Integer codigoUsuario);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usuarios
     *
     * @mbggenerated Tue Feb 11 16:49:30 BOT 2014
     */
    int updateByExampleSelective(@Param("record") Usuario record, @Param("example") UsuarioExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usuarios
     *
     * @mbggenerated Tue Feb 11 16:49:30 BOT 2014
     */
    int updateByExample(@Param("record") Usuario record, @Param("example") UsuarioExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usuarios
     *
     * @mbggenerated Tue Feb 11 16:49:30 BOT 2014
     */
    int updateByPrimaryKeySelective(Usuario record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usuarios
     *
     * @mbggenerated Tue Feb 11 16:49:30 BOT 2014
     */
    int updateByPrimaryKey(Usuario record);

	int obtenerFechaHoraServidor(Map<String, Date> mapa);

	void obtenerUltimoId(Map<String, Integer> mapa);
}